import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Text } from '@/components/AppText';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, Chip, Field, ProgressBar } from '@/components/ui';
import { colors, radius, spacing } from '@/constants/theme';
import { motivations } from '@/data/catalog';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import { kgToPounds, poundsToKg } from '@/utils/health';

const goals = ['Lose weight', 'Maintain weight', 'Gain healthy weight', 'Build muscle', 'Improve endurance', 'Become more active', 'Improve overall health', 'Combination of goals'];
const progressOptions = ['Target weight', 'Muscle-building focus', 'Fitness consistency', 'Better nutrition', 'Increased activity', 'Improved energy', 'No specific weight target'];
const activity = ['Mostly sedentary', 'Lightly active', 'Moderately active', 'Very active', 'Highly active / athlete'];
const interests = ['Walking', 'Running', 'Weightlifting', 'Bodyweight workouts', 'HIIT', 'Cycling', 'Swimming', 'Sports', 'Yoga/stretching', 'General fitness', 'Not sure yet'];
const equipment = ['Full gym', 'Dumbbells', 'Resistance bands', 'Home equipment', 'No equipment'];
const diets = ['Omnivore', 'Vegetarian', 'Vegan', 'Pescatarian', 'Low-carb preference', 'High-protein preference', 'No specific diet'];
const wellness = ['Stress', 'Anxiety', 'Motivation', 'Sleep', 'Confidence', 'Staying consistent', 'Mood', 'Mindfulness', 'None right now'];
const recoveryOptions = [{ value: 'yes', label: 'Yes, include recovery support' }, { value: 'later', label: 'Maybe later' }, { value: 'no', label: 'No, not right now' }] as const;

const copy = [
  ['About you', 'A few basics help us give useful context.'], ['Your goals', 'Choose everything that feels meaningful right now.'], ['Define progress', 'Progress can be about much more than a number.'], ['Daily activity', 'Which option best matches an average week?'], ['Movement you enjoy', 'We’ll use this to keep workouts realistic.'], ['Nutrition preferences', 'We will always filter out recorded allergens.'], ['Foods you enjoy', 'Variety starts with learning your actual tastes.'], ['Mental wellness', 'This is wellness support, never a diagnosis.'], ['Recovery support', 'This choice is private and can be changed anytime.'], ['Your reason', 'We’ll bring this back when a day feels difficult.'],
] as const;

export default function OnboardingStep() {
  const params = useLocalSearchParams<{ step: string }>(); const step = Math.max(1, Math.min(10, Number(params.step) || 1)); const theme = useTheme(); const { data, updateOnboarding } = useApp(); const answers = data.onboarding; const [error, setError] = useState('');
  const [age, setAge] = useState(String(answers.age ?? '')); const [height, setHeight] = useState(String(answers.heightCm ? Math.round(answers.heightCm) : '')); const displayWeight = answers.currentWeightKg ? (answers.units === 'imperial' ? kgToPounds(answers.currentWeightKg) : answers.currentWeightKg) : undefined; const [weight, setWeight] = useState(String(displayWeight ? Math.round(displayWeight) : '')); const [allergies, setAllergies] = useState(answers.allergies.join(', ')); const [liked, setLiked] = useState(answers.likedFoods.join(', ')); const [disliked, setDisliked] = useState(answers.dislikedFoods.join(', ')); const [customMotivation, setCustomMotivation] = useState('');
  const title = copy[step - 1]?.[0] ?? ''; const subtitle = copy[step - 1]?.[1] ?? '';
  const toggle = (key: 'goals' | 'fitnessInterests' | 'equipment' | 'wellnessAreas', item: string) => updateOnboarding({ [key]: answers[key].includes(item) ? answers[key].filter((value) => value !== item) : [...answers[key], item] });
  const canContinue = useMemo(() => { if (step === 1) return Number(age) >= 18 && Number(height) > 0 && Number(weight) > 0; if (step === 2) return answers.goals.length > 0; if (step === 3) return Boolean(answers.progressVision); if (step === 4) return Boolean(answers.activityLevel); if (step === 5) return answers.fitnessInterests.length > 0 && answers.equipment.length > 0; if (step === 6) return Boolean(answers.diet); if (step === 8) return answers.wellnessAreas.length > 0; if (step === 9) return Boolean(answers.recoveryChoice); if (step === 10) return Boolean(answers.motivation || customMotivation.trim()); return true; }, [step, age, height, weight, answers, customMotivation]);
  const next = () => { setError(''); if (!canContinue) { setError(step === 1 && Number(age) < 18 ? 'Sober Plus Health is currently designed for adults age 18 and older.' : 'Choose an option to continue.'); return; } if (step === 1) updateOnboarding({ age: Number(age), heightCm: Number(height), currentWeightKg: answers.units === 'imperial' ? poundsToKg(Number(weight)) : Number(weight) }); if (step === 6) updateOnboarding({ allergies: split(allergies) }); if (step === 7) updateOnboarding({ likedFoods: split(liked), dislikedFoods: split(disliked) }); if (step === 10 && customMotivation.trim()) updateOnboarding({ motivation: customMotivation.trim() }); router.push(step === 10 ? '/onboarding/result' : `/onboarding/${step + 1}` as never); };
  const back = () => step === 1 ? router.replace('/sign-up') : router.back();

  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.colors.background }]}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.safe}><View style={styles.top}><Pressable accessibilityLabel="Go back" onPress={back} style={[styles.back, { borderColor: theme.colors.border }]}><Ionicons name="arrow-back" size={21} color={theme.colors.text} /></Pressable><View style={styles.progress}><Text style={[styles.count, { color: theme.colors.muted }]}>{step} of 10</Text><ProgressBar value={step * 10} /></View><View style={styles.back} /></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.scroll}><View style={styles.shell}><Text style={[styles.title, { color: theme.colors.text }]}>{title}</Text><Text style={[styles.subtitle, { color: theme.colors.muted }]}>{subtitle}</Text><View style={styles.question}>{renderQuestion()}</View>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}</View></ScrollView><View style={[styles.footer, { borderColor: theme.colors.border, backgroundColor: theme.colors.background }]}><Button label={step === 10 ? 'See my plan' : 'Continue'} icon="arrow-forward" onPress={next} /></View></KeyboardAvoidingView></SafeAreaView>;

  function renderQuestion() {
    switch (step) {
      case 1: return <><View style={styles.row}><Chip label="Imperial" selected={answers.units === 'imperial'} onPress={() => updateOnboarding({ units: 'imperial' })} /><Chip label="Metric" selected={answers.units === 'metric'} onPress={() => updateOnboarding({ units: 'metric' })} /></View><Field label="Age" keyboardType="number-pad" placeholder="34" value={age} onChangeText={setAge} /><Field label="Height (centimeters)" keyboardType="decimal-pad" placeholder="178" value={height} onChangeText={setHeight} /><Field label={`Current weight (${answers.units === 'imperial' ? 'lb' : 'kg'})`} keyboardType="decimal-pad" placeholder={answers.units === 'imperial' ? '180' : '82'} value={weight} onChangeText={setWeight} /><Text style={[styles.helper, { color: theme.colors.muted }]}>You can change units and measurements later in Settings.</Text></>;
      case 2: return <ChoiceWrap>{goals.map((item) => <Chip key={item} label={item} selected={answers.goals.includes(item)} onPress={() => toggle('goals', item)} />)}</ChoiceWrap>;
      case 3: return <><ChoiceWrap>{progressOptions.map((item) => <Chip key={item} label={item} selected={answers.progressVision === item} onPress={() => updateOnboarding({ progressVision: item })} />)}</ChoiceWrap>{answers.progressVision === 'Target weight' ? <Field label={`Target weight (${answers.units === 'imperial' ? 'lb' : 'kg'})`} keyboardType="decimal-pad" placeholder="Optional" onChangeText={(value) => updateOnboarding({ targetWeightKg: answers.units === 'imperial' ? poundsToKg(Number(value)) : Number(value) })} /> : null}</>;
      case 4: return <View style={styles.stack}>{activity.map((item) => <ChoiceRow key={item} label={item} selected={answers.activityLevel === item} onPress={() => updateOnboarding({ activityLevel: item })} />)}</View>;
      case 5: return <><Text style={[styles.groupLabel, { color: theme.colors.text }]}>I’m interested in</Text><ChoiceWrap>{interests.map((item) => <Chip key={item} label={item} selected={answers.fitnessInterests.includes(item)} onPress={() => toggle('fitnessInterests', item)} />)}</ChoiceWrap><Text style={[styles.groupLabel, { color: theme.colors.text }]}>Equipment available</Text><ChoiceWrap>{equipment.map((item) => <Chip key={item} label={item} selected={answers.equipment.includes(item)} onPress={() => toggle('equipment', item)} />)}</ChoiceWrap></>;
      case 6: return <><ChoiceWrap>{diets.map((item) => <Chip key={item} label={item} selected={answers.diet === item} onPress={() => updateOnboarding({ diet: item })} />)}</ChoiceWrap><Field label="Allergies or foods to avoid" placeholder="e.g. peanuts, shellfish" value={allergies} onChangeText={setAllergies} /><View style={styles.safety}><Ionicons name="shield-checkmark" size={19} color={colors.success} /><Text style={[styles.safetyText, { color: theme.colors.text }]}>Recorded allergens are excluded from recommendations.</Text></View></>;
      case 7: return <><Field label="Foods or cuisines you enjoy" placeholder="e.g. Mexican, salmon, berries" value={liked} onChangeText={setLiked} /><Field label="Foods you don’t enjoy" placeholder="e.g. olives, mushrooms" value={disliked} onChangeText={setDisliked} /><Text style={[styles.helper, { color: theme.colors.muted }]}>Separate items with commas. You can skip either field.</Text></>;
      case 8: return <ChoiceWrap>{wellness.map((item) => <Chip key={item} label={item} selected={answers.wellnessAreas.includes(item)} onPress={() => toggle('wellnessAreas', item)} />)}</ChoiceWrap>;
      case 9: return <><View style={styles.stack}>{recoveryOptions.map((item) => <ChoiceRow key={item.value} label={item.label} selected={answers.recoveryChoice === item.value} onPress={() => updateOnboarding({ recoveryChoice: item.value })} />)}</View>{answers.recoveryChoice === 'yes' ? <><Field label="Recovery goal or category (optional)" placeholder="e.g. Alcohol-free" value={answers.recoveryCategory ?? ''} onChangeText={(value) => updateOnboarding({ recoveryCategory: value })} /><Field label="Start date (YYYY-MM-DD, optional)" placeholder="2026-01-15" value={answers.soberStartDate ?? ''} onChangeText={(value) => updateOnboarding({ soberStartDate: value })} /></> : null}<Text style={[styles.helper, { color: theme.colors.muted }]}>You never have to disclose a substance or category.</Text></>;
      case 10: return <><ChoiceWrap>{motivations.map((item) => <Chip key={item} label={item} selected={answers.motivation === item} onPress={() => { updateOnboarding({ motivation: item }); setCustomMotivation(''); }} />)}</ChoiceWrap><Field label="Or write it in your own words" placeholder="I want to feel present for…" value={customMotivation} onChangeText={setCustomMotivation} multiline style={{ minHeight: 90, paddingTop: 15 }} /></>;
      default: return null;
    }
  }
}

const split = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean);
function ChoiceWrap({ children }: React.PropsWithChildren) { return <View style={styles.row}>{children}</View>; }
function ChoiceRow({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { const theme = useTheme(); return <Pressable onPress={onPress} style={[styles.choice, { borderColor: selected ? colors.purple : theme.colors.border, backgroundColor: selected ? (theme.isDark ? '#33235E' : '#F3EDFF') : theme.colors.surface }]}><View style={[styles.radio, { borderColor: selected ? colors.purple : theme.colors.muted }]}>{selected ? <View style={styles.radioDot} /> : null}</View><Text style={[styles.choiceText, { color: theme.colors.text }]}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({ safe: { flex: 1 }, top: { flexDirection: 'row', alignItems: 'center', gap: 16, maxWidth: 720, width: '100%', alignSelf: 'center', paddingHorizontal: spacing.lg, paddingTop: 6 }, back: { width: 42, height: 42, borderRadius: radius.md, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, progress: { flex: 1 }, count: { fontSize: 11, fontWeight: '600', marginBottom: 6, textAlign: 'center' }, scroll: { flexGrow: 1, paddingHorizontal: spacing.xl, paddingVertical: 32 }, shell: { width: '100%', maxWidth: 600, alignSelf: 'center' }, title: { fontSize: 29, lineHeight: 36, fontWeight: '700', letterSpacing: -0.55 }, subtitle: { fontSize: 15, lineHeight: 23, marginTop: 6 }, question: { gap: 17, marginTop: 28 }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, stack: { gap: 8 }, groupLabel: { fontSize: 15, fontWeight: '600', marginTop: 4 }, helper: { fontSize: 11, lineHeight: 17 }, error: { color: colors.coral, fontSize: 12, fontWeight: '600', marginTop: 16 }, safety: { flexDirection: 'row', alignItems: 'center', gap: 9, borderRadius: radius.md, backgroundColor: '#16836B18', padding: 12 }, safetyText: { flex: 1, fontSize: 12, fontWeight: '500' }, choice: { minHeight: 54, borderWidth: 1, borderRadius: radius.md, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, gap: 11 }, radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' }, radioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.purple }, choiceText: { fontSize: 14, fontWeight: '500', flex: 1 }, footer: { borderTopWidth: 1, paddingHorizontal: spacing.xl, paddingVertical: 12 }, });
