import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, View, useWindowDimensions } from 'react-native';
import { Text } from '@/components/AppText';
import { AppScreen, Button, Chip, Header, SectionTitle } from '@/components/ui';
import { colors, radius, typeScale } from '@/constants/theme';
import { bowlBases, bowlBeans, bowlProteins, bowlToppings, calculateBowl, defaultBowl, type BowlOption } from '@/data/bowl';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import type { CustomBowlSelection } from '@/types/models';
import { formatQuantity } from '@/utils/grocery';

export default function BuildBowlScreen() {
  const theme = useTheme(); const { width } = useWindowDimensions(); const { saveBowl, addBowlToGrocery, logBowl } = useApp(); const [selection, setSelection] = useState<CustomBowlSelection>(defaultBowl); const [notice, setNotice] = useState(''); const nutrition = useMemo(() => calculateBowl(selection), [selection]); const wide = width >= 820;
  const protein = bowlProteins.find((option) => option.id === selection.protein)?.label ?? 'Custom'; const base = bowlBases.find((option) => option.id === selection.base)?.label ?? 'bowl'; const title = `${protein} ${base.toLowerCase()} bowl`;
  return <AppScreen><Pressable accessibilityRole="button" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={theme.colors.text} /><Text style={[styles.backText, { color: theme.colors.text }]}>Nutrition</Text></Pressable><Header title="Build Your Own Bowl" subtitle="Choose what sounds good. Nutrition updates with every selection." />
    <View style={[styles.layout, !wide && styles.stack]}><View style={styles.builder}><OptionSection title="Base" subtitle="Choose one" options={bowlBases} selected={[selection.base]} onPress={(id) => setSelection((current) => ({ ...current, base: id }))} /><OptionSection title="Protein" subtitle="Choose one" options={bowlProteins} selected={[selection.protein]} onPress={(id) => setSelection((current) => ({ ...current, protein: id }))} /><OptionSection title="Beans" subtitle="Choose one" options={bowlBeans} selected={[selection.beans]} onPress={(id) => setSelection((current) => ({ ...current, beans: id }))} /><OptionSection title="Toppings" subtitle="Choose as many as you like" options={bowlToppings} selected={selection.toppings} onPress={(id) => setSelection((current) => ({ ...current, toppings: current.toppings.includes(id) ? current.toppings.filter((item) => item !== id) : [...current.toppings, id] }))} /></View>
      <View style={[styles.summary, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><Text style={styles.eyebrow}>YOUR BOWL</Text><Text style={[styles.summaryTitle, { color: theme.colors.text }]}>{title}</Text><View style={styles.macros}><Macro value={nutrition.calories} label="calories" /><Macro value={`${nutrition.protein}g`} label="protein" /><Macro value={`${nutrition.carbs}g`} label="carbs" /><Macro value={`${nutrition.fat}g`} label="fat" /></View><View style={[styles.rule, { backgroundColor: theme.colors.border }]} /><Text style={[styles.summaryLabel, { color: theme.colors.text }]}>Selected ingredients</Text>{nutrition.ingredients.map((ingredient) => <View key={`${ingredient.name}-${ingredient.unit}`} style={styles.selectedIngredient}><Text style={[styles.ingredientName, { color: theme.colors.muted }]}>{ingredient.name}</Text><Text style={[styles.ingredientQty, { color: theme.colors.text }]}>{formatQuantity(ingredient.amount, ingredient.unit)}</Text></View>)}{notice ? <View style={[styles.notice, { backgroundColor: theme.isDark ? '#12302B' : colors.successSoft }]}><Ionicons name="checkmark-circle" size={17} color={colors.success} /><Text style={[styles.noticeText, { color: theme.isDark ? '#9CE0CF' : colors.success }]}>{notice}</Text></View> : null}<View style={styles.actions}><Button label="Save bowl" icon="heart-outline" onPress={() => { saveBowl(title, selection); setNotice('Bowl saved to My Favorites.'); }} /><Button label="Log as meal" icon="checkmark-circle-outline" variant="secondary" onPress={() => { logBowl(title); setNotice('Bowl logged for today.'); }} /><Button label="Add ingredients to grocery list" icon="basket-outline" variant="secondary" onPress={() => { addBowlToGrocery(title, selection); setNotice('Ingredients added and combined.'); }} /></View></View></View>
  </AppScreen>;
}

function OptionSection({ title, subtitle, options, selected, onPress }: { title: string; subtitle: string; options: BowlOption[]; selected: string[]; onPress: (id: string) => void }) { return <View><SectionTitle eyebrow={subtitle.toUpperCase()} title={title} /><View style={styles.options}>{options.map((option) => <Chip key={option.id} label={option.label} selected={selected.includes(option.id)} onPress={() => onPress(option.id)} />)}</View></View>; }
function Macro({ value, label }: { value: string | number; label: string }) { const theme = useTheme(); return <View style={styles.macro}><Text style={[styles.macroValue, { color: theme.colors.text }]}>{value}</Text><Text style={[styles.macroLabel, { color: theme.colors.muted }]}>{label}</Text></View>; }

const styles = StyleSheet.create({ back: { alignSelf: 'flex-start', minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 8 }, backText: { ...typeScale.body, fontWeight: '600' }, layout: { flexDirection: 'row', alignItems: 'flex-start', gap: 24 }, stack: { flexDirection: 'column' }, builder: { flex: 1.2, width: '100%', gap: 24 }, options: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: -8 }, summary: { flex: .8, width: '100%', borderWidth: 1, borderRadius: radius.lg, padding: 18 }, eyebrow: { color: colors.purple, ...typeScale.caption, letterSpacing: 1.3, fontWeight: '600' }, summaryTitle: { ...typeScale.section, fontWeight: '700', marginTop: 4, textTransform: 'capitalize' }, macros: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 18 }, macro: { flex: 1, minWidth: 70 }, macroValue: { fontSize: 21, lineHeight: 27, fontWeight: '700' }, macroLabel: { ...typeScale.caption }, rule: { height: 1, marginVertical: 17 }, summaryLabel: { ...typeScale.body, fontWeight: '600', marginBottom: 5 }, selectedIngredient: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, paddingVertical: 5 }, ingredientName: { ...typeScale.label, textTransform: 'capitalize' }, ingredientQty: { ...typeScale.label, fontWeight: '600' }, notice: { marginTop: 14, borderRadius: radius.md, padding: 9, flexDirection: 'row', gap: 7, alignItems: 'center' }, noticeText: { ...typeScale.label, fontWeight: '600', flex: 1 }, actions: { marginTop: 16, gap: 8 } });
