import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { Text } from '@/components/AppText';
import { NutritionNav } from '@/components/NutritionUI';
import { AppScreen, Button, Chip, EmptyState, Header, SectionTitle } from '@/components/ui';
import { colors, radius, typeScale } from '@/constants/theme';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import type { GroceryCategory, GroceryItem } from '@/types/models';
import { formatQuantity } from '@/utils/grocery';

const categories: GroceryCategory[] = ['Produce', 'Meat & Protein', 'Grains & Bakery', 'Dairy & Refrigerated', 'Canned & Pantry', 'Frozen', 'Other'];
const units = ['whole', 'oz', 'lb', 'cup', 'tbsp', 'tsp', 'package'];

export default function GroceryListScreen() {
  const theme = useTheme(); const { data, toggleGroceryItem, addCustomGroceryItem, updateGroceryAmount, removeGroceryItem, removeGrocerySource, clearCompletedGroceries, clearGroceryList } = useApp(); const [adding, setAdding] = useState(false); const [name, setName] = useState(''); const [amount, setAmount] = useState('1'); const [unit, setUnit] = useState('whole'); const [category, setCategory] = useState<GroceryCategory>('Produce');
  const completed = data.groceryItems.filter((item) => item.checked).length; const sources = useMemo(() => Array.from(new Map(data.groceryItems.flatMap((item) => item.sources).filter((source) => !source.id.startsWith('custom:')).map((source) => [source.id, source])).values()), [data.groceryItems]);
  const add = () => { const quantity = Number(amount); if (!name.trim() || !Number.isFinite(quantity) || quantity <= 0) return; addCustomGroceryItem(name.trim(), quantity, unit, category); setName(''); setAmount('1'); setAdding(false); };
  return <AppScreen><Header title="Grocery List" subtitle="Combined ingredients, organized for the way you shop." /><NutritionNav current="grocery" />
    <View style={[styles.summary, { borderColor: theme.colors.border }]}><View style={styles.summaryItem}><Text style={[styles.summaryValue, { color: theme.colors.text }]}>{data.groceryItems.length}</Text><Text style={[styles.summaryLabel, { color: theme.colors.muted }]}>items</Text></View><View style={styles.summaryItem}><Text style={[styles.summaryValue, { color: theme.colors.text }]}>{completed}</Text><Text style={[styles.summaryLabel, { color: theme.colors.muted }]}>checked off</Text></View><View style={styles.summaryActions}><Button label="Add item" icon="add" variant="secondary" onPress={() => setAdding((value) => !value)} /><Button label="Find recipes" icon="restaurant-outline" variant="ghost" onPress={() => router.push('/(tabs)/nutrition')} /></View></View>
    {adding ? <View style={[styles.addPanel, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><Text style={[styles.panelTitle, { color: theme.colors.text }]}>Add your own item</Text><View style={styles.addFields}><TextInput accessibilityLabel="Grocery item name" autoFocus value={name} onChangeText={setName} placeholder="Item name" placeholderTextColor={theme.colors.faint} style={[styles.input, styles.nameInput, { borderColor: theme.colors.strongBorder, color: theme.colors.text }]} /><TextInput accessibilityLabel="Quantity" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" style={[styles.input, styles.amountInput, { borderColor: theme.colors.strongBorder, color: theme.colors.text }]} /></View><Text style={[styles.fieldLabel, { color: theme.colors.muted }]}>UNIT</Text><View style={styles.chips}>{units.map((item) => <Chip key={item} label={item} selected={unit === item} onPress={() => setUnit(item)} />)}</View><Text style={[styles.fieldLabel, { color: theme.colors.muted }]}>AISLE</Text><View style={styles.chips}>{categories.map((item) => <Chip key={item} label={item} selected={category === item} onPress={() => setCategory(item)} />)}</View><View style={styles.addActions}><Button label="Add to list" onPress={add} /><Button label="Cancel" variant="ghost" onPress={() => setAdding(false)} /></View></View> : null}
    {sources.length ? <View><SectionTitle eyebrow="SHOPPING FOR" title={`${sources.length} recipe${sources.length === 1 ? '' : 's'} or bowl${sources.length === 1 ? '' : 's'}`} /><View style={styles.sources}>{sources.map((source) => <View key={source.id} style={[styles.source, { backgroundColor: theme.colors.surfaceSubtle }]}><Text numberOfLines={1} style={[styles.sourceLabel, { color: theme.colors.text }]}>{source.label}</Text><Pressable accessibilityLabel={`Remove ${source.label} ingredients`} onPress={() => removeGrocerySource(source.id)} style={styles.sourceRemove}><Ionicons name="close" size={16} color={theme.colors.muted} /></Pressable></View>)}</View></View> : null}
    {data.groceryItems.length ? <View>{categories.map((group) => { const items = data.groceryItems.filter((item) => item.category === group); return items.length ? <View key={group} style={styles.group}><Text style={styles.groupTitle}>{group.toUpperCase()}</Text>{items.map((item) => <GroceryRow key={item.id} item={item} onToggle={() => toggleGroceryItem(item.id)} onAmount={(value) => updateGroceryAmount(item.id, value)} onDelete={() => removeGroceryItem(item.id)} />)}</View> : null; })}<View style={[styles.clearRow, { borderColor: theme.colors.border }]}><Button label="Clear completed" icon="checkmark-done-outline" variant="secondary" disabled={!completed} onPress={clearCompletedGroceries} /><Button label="Clear entire list" icon="trash-outline" variant="ghost" onPress={() => Alert.alert('Clear grocery list?', 'This removes every item from your list.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Clear list', style: 'destructive', onPress: clearGroceryList }])} /></View></View> : <EmptyState icon="basket-outline" title="Your grocery list is ready when you are" body="Add a recipe, build a custom bowl, or create a list from your weekly plan. Shared ingredients will combine automatically." action={<Button label="Browse recipes" onPress={() => router.push('/(tabs)/nutrition')} />} />}
  </AppScreen>;
}

function GroceryRow({ item, onToggle, onAmount, onDelete }: { item: GroceryItem; onToggle: () => void; onAmount: (amount: number) => void; onDelete: () => void }) { const theme = useTheme(); const step = item.unit === 'whole' || item.unit === 'package' ? 1 : .25; return <View style={[styles.item, { borderColor: theme.colors.border }]}><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: item.checked }} accessibilityLabel={`${item.name}, ${formatQuantity(item.amount, item.unit)}`} onPress={onToggle} style={[styles.checkbox, { borderColor: item.checked ? colors.success : theme.colors.strongBorder, backgroundColor: item.checked ? colors.success : 'transparent' }]}>{item.checked ? <Ionicons name="checkmark" size={14} color={colors.white} /> : null}</Pressable><View style={styles.itemCopy}><Text style={[styles.itemName, { color: item.checked ? theme.colors.faint : theme.colors.text }, item.checked && styles.done]}>{item.name}</Text><Text numberOfLines={2} style={[styles.itemSources, { color: theme.colors.muted }]}>For {item.sources.map((source) => source.label).join(', ')}</Text></View><View style={[styles.quantityControl, { borderColor: theme.colors.border }]}><Pressable accessibilityLabel={`Decrease ${item.name} quantity`} onPress={() => onAmount(Math.max(step, item.amount - step))} style={styles.quantityButton}><Ionicons name="remove" size={15} color={theme.colors.muted} /></Pressable><Text style={[styles.quantityText, { color: theme.colors.text }]}>{formatQuantity(item.amount, item.unit)}</Text><Pressable accessibilityLabel={`Increase ${item.name} quantity`} onPress={() => onAmount(item.amount + step)} style={styles.quantityButton}><Ionicons name="add" size={15} color={theme.colors.muted} /></Pressable></View><Pressable accessibilityLabel={`Delete ${item.name}`} onPress={onDelete} style={styles.delete}><Ionicons name="trash-outline" size={18} color={theme.colors.faint} /></Pressable></View>; }

const styles = StyleSheet.create({ summary: { borderTopWidth: 1, borderBottomWidth: 1, paddingVertical: 14, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 18 }, summaryItem: { minWidth: 85 }, summaryValue: { fontSize: 24, lineHeight: 29, fontWeight: '700' }, summaryLabel: { ...typeScale.caption }, summaryActions: { flex: 1, minWidth: 240, flexDirection: 'row', justifyContent: 'flex-end', flexWrap: 'wrap', gap: 8 }, addPanel: { borderWidth: 1, borderRadius: radius.lg, padding: 16, gap: 10 }, panelTitle: { ...typeScale.section, fontWeight: '700' }, addFields: { flexDirection: 'row', gap: 8 }, input: { minHeight: 46, borderWidth: 1, borderRadius: radius.md, paddingHorizontal: 12, fontSize: 14, outlineStyle: 'none' } as never, nameInput: { flex: 1 }, amountInput: { width: 88 }, fieldLabel: { ...typeScale.caption, fontWeight: '600', letterSpacing: 1, marginTop: 3 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, addActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 }, sources: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: -8 }, source: { borderRadius: radius.md, minHeight: 36, paddingLeft: 10, flexDirection: 'row', alignItems: 'center', maxWidth: 260 }, sourceLabel: { ...typeScale.label, fontWeight: '500', flexShrink: 1 }, sourceRemove: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center' }, group: { marginTop: 4 }, groupTitle: { color: colors.purple, ...typeScale.caption, fontWeight: '600', letterSpacing: 1.2, marginBottom: 3 }, item: { minHeight: 64, borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 10 }, checkbox: { width: 23, height: 23, borderRadius: radius.sm, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' }, itemCopy: { flex: 1, minWidth: 100 }, itemName: { ...typeScale.body, fontWeight: '600', textTransform: 'capitalize' }, itemSources: { ...typeScale.caption, marginTop: 1 }, done: { textDecorationLine: 'line-through' }, quantityControl: { height: 36, borderWidth: 1, borderRadius: radius.md, flexDirection: 'row', alignItems: 'center' }, quantityButton: { width: 32, height: 34, alignItems: 'center', justifyContent: 'center' }, quantityText: { ...typeScale.caption, fontWeight: '600', minWidth: 48, textAlign: 'center' }, delete: { width: 36, height: 40, alignItems: 'center', justifyContent: 'center' }, clearRow: { borderTopWidth: 1, paddingTop: 16, marginTop: 16, flexDirection: 'row', flexWrap: 'wrap', gap: 8 } });
