import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useDeferredValue, useMemo, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View, useWindowDimensions } from 'react-native';
import { Text } from '@/components/AppText';
import { NutritionNav } from '@/components/NutritionUI';
import { AppScreen, Button, Chip, Header, SectionTitle } from '@/components/ui';
import { colors, radius, typeScale } from '@/constants/theme';
import { meals } from '@/data/catalog';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import type { MealPlanDay, MealPlanSlot } from '@/types/models';

const days: MealPlanDay[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const slots: MealPlanSlot[] = ['Breakfast', 'Lunch', 'Dinner', 'Snack'];

export default function MealPlanScreen() {
  const { mealId } = useLocalSearchParams<{ mealId?: string }>(); const theme = useTheme(); const { width } = useWindowDimensions(); const { data, setMealPlan, createGroceryFromPlan } = useApp(); const incoming = meals.find((meal) => meal.id === mealId); const [picker, setPicker] = useState<{ day: MealPlanDay; slot: MealPlanSlot } | null>(incoming ? { day: 'Monday', slot: incoming.category === 'Snack' ? 'Snack' : incoming.category === 'Breakfast' ? 'Breakfast' : incoming.category === 'Lunch' ? 'Lunch' : 'Dinner' } : null); const [search, setSearch] = useState(''); const [notice, setNotice] = useState(''); const deferredSearch = useDeferredValue(search.toLowerCase()); const wide = width >= 760;
  const pickerMeals = useMemo(() => meals.filter((meal) => (!picker || picker.slot === 'Snack' ? meal.category === 'Snack' : meal.category === picker?.slot) && (!deferredSearch || `${meal.title} ${meal.ingredients.map((ingredient) => ingredient.name).join(' ')}`.toLowerCase().includes(deferredSearch))), [deferredSearch, picker]);
  const assign = (id: string) => { if (!picker) return; setMealPlan(picker.day, picker.slot, id); setNotice(`${meals.find((meal) => meal.id === id)?.title ?? 'Meal'} added to ${picker.day} ${picker.slot.toLowerCase()}.`); setPicker(null); setSearch(''); if (incoming) router.replace('/meal-plan'); };
  return <AppScreen><Header title="Weekly Meal Plan" subtitle="Plan familiar meals first, then create one combined shopping list." /><NutritionNav current="plan" />
    <View style={[styles.summary, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><View style={styles.flex}><Text style={[styles.summaryValue, { color: theme.colors.text }]}>{data.mealPlan.length} / 28 slots</Text><Text style={[styles.summaryDetail, { color: theme.colors.muted }]}>Plan as much or as little as is useful.</Text></View><Button label="Create grocery list" icon="basket-outline" onPress={() => { createGroceryFromPlan(); setNotice('Your grocery list now includes every planned meal.'); }} /></View>
    {notice ? <View style={[styles.notice, { backgroundColor: theme.isDark ? '#12302B' : colors.successSoft }]}><Ionicons name="checkmark-circle" size={18} color={colors.success} /><Text style={[styles.noticeText, { color: theme.isDark ? '#9CE0CF' : colors.success }]}>{notice}</Text></View> : null}
    {incoming && picker ? <View style={[styles.incoming, { borderColor: colors.purple }]}><Text style={styles.eyebrow}>ADD THIS RECIPE</Text><Text style={[styles.incomingTitle, { color: theme.colors.text }]}>{incoming.title}</Text><Text style={[styles.helper, { color: theme.colors.muted }]}>Choose where it belongs, then add it.</Text><View style={styles.selectorRow}>{days.map((day) => <Chip key={day} label={day.slice(0, 3)} selected={picker.day === day} onPress={() => setPicker((current) => current ? { ...current, day } : current)} />)}</View><View style={styles.selectorRow}>{slots.map((slot) => <Chip key={slot} label={slot} selected={picker.slot === slot} onPress={() => setPicker((current) => current ? { ...current, slot } : current)} />)}</View><Button label="Add to plan" icon="calendar-outline" onPress={() => assign(incoming.id)} /></View> : null}
    {picker && !incoming ? <View style={[styles.picker, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><View style={styles.pickerHeader}><View><Text style={styles.eyebrow}>CHOOSE A MEAL</Text><Text style={[styles.pickerTitle, { color: theme.colors.text }]}>{picker.day} · {picker.slot}</Text></View><Pressable accessibilityLabel="Close meal picker" onPress={() => setPicker(null)} style={styles.close}><Ionicons name="close" size={21} color={theme.colors.text} /></Pressable></View><View style={[styles.search, { borderColor: theme.colors.strongBorder }]}><Ionicons name="search" size={17} color={theme.colors.faint} /><TextInput value={search} onChangeText={setSearch} placeholder="Search meals or ingredients" placeholderTextColor={theme.colors.faint} style={[styles.searchInput, { color: theme.colors.text }]} /></View><View style={styles.pickerList}>{pickerMeals.map((meal) => <Pressable key={meal.id} accessibilityRole="button" onPress={() => assign(meal.id)} style={({ pressed }) => [styles.pickerMeal, { borderColor: theme.colors.border }, pressed && styles.pressed]}><View style={styles.flex}><Text style={[styles.pickerMealTitle, { color: theme.colors.text }]}>{meal.title}</Text><Text style={[styles.pickerMealMeta, { color: theme.colors.muted }]}>{meal.calories} cal · {meal.protein}g protein · {meal.time} min</Text></View><Ionicons name="add-circle-outline" size={21} color={colors.purple} /></Pressable>)}</View></View> : null}
    <View><SectionTitle eyebrow="MONDAY — SUNDAY" title="Your week" /><View style={styles.dayGrid}>{days.map((day) => <View key={day} style={[styles.day, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }, wide && styles.dayWide]}><Text style={[styles.dayTitle, { color: theme.colors.text }]}>{day}</Text>{slots.map((slot) => { const entry = data.mealPlan.find((item) => item.day === day && item.slot === slot); const selected = meals.find((meal) => meal.id === entry?.mealId); return <View key={slot} style={[styles.slot, { borderColor: theme.colors.border }]}><View style={styles.slotCopy}><Text style={[styles.slotLabel, { color: theme.colors.faint }]}>{slot.toUpperCase()}</Text><Text numberOfLines={1} style={[styles.slotMeal, { color: selected ? theme.colors.text : theme.colors.muted }]}>{selected?.title ?? 'Choose a meal'}</Text></View><View style={styles.slotActions}><Pressable accessibilityLabel={`${selected ? 'Change' : 'Add'} ${day} ${slot}`} onPress={() => { setPicker({ day, slot }); setNotice(''); }} style={styles.smallButton}><Ionicons name={selected ? 'swap-horizontal-outline' : 'add'} size={18} color={colors.purple} /></Pressable>{selected ? <Pressable accessibilityLabel={`Remove ${selected.title} from plan`} onPress={() => setMealPlan(day, slot)} style={styles.smallButton}><Ionicons name="close" size={18} color={theme.colors.faint} /></Pressable> : null}</View></View>; })}</View>)}</View></View>
  </AppScreen>;
}

const styles = StyleSheet.create({ summary: { borderWidth: 1, borderRadius: radius.lg, padding: 16, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 14 }, flex: { flex: 1, minWidth: 180 }, summaryValue: { ...typeScale.section, fontWeight: '700' }, summaryDetail: { ...typeScale.body, marginTop: 2 }, notice: { borderRadius: radius.md, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 8 }, noticeText: { ...typeScale.label, fontWeight: '600', flex: 1 }, incoming: { borderLeftWidth: 3, paddingLeft: 16, gap: 11 }, eyebrow: { color: colors.purple, ...typeScale.caption, letterSpacing: 1.2, fontWeight: '600' }, incomingTitle: { ...typeScale.section, fontWeight: '700' }, helper: { ...typeScale.body }, selectorRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, picker: { borderWidth: 1, borderRadius: radius.lg, padding: 16 }, pickerHeader: { flexDirection: 'row', justifyContent: 'space-between' }, pickerTitle: { ...typeScale.section, fontWeight: '700', marginTop: 2 }, close: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' }, search: { minHeight: 45, borderWidth: 1, borderRadius: radius.md, marginTop: 12, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8 }, searchInput: { flex: 1, fontSize: 14, outlineStyle: 'none' } as never, pickerList: { marginTop: 8, maxHeight: 420, overflow: 'scroll' }, pickerMeal: { borderTopWidth: 1, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', gap: 10 }, pickerMealTitle: { ...typeScale.body, fontWeight: '600' }, pickerMealMeta: { ...typeScale.caption, marginTop: 2 }, dayGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, day: { width: '100%', borderWidth: 1, borderRadius: radius.lg, padding: 14 }, dayWide: { width: 'calc(50% - 7px)' as never }, dayTitle: { ...typeScale.bodyLarge, fontWeight: '700', marginBottom: 5 }, slot: { minHeight: 55, borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 8 }, slotCopy: { flex: 1 }, slotLabel: { ...typeScale.caption, fontWeight: '600', letterSpacing: .7 }, slotMeal: { ...typeScale.body, fontWeight: '500', marginTop: 1 }, slotActions: { flexDirection: 'row' }, smallButton: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' }, pressed: { opacity: .72 } });
