import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Text } from '@/components/AppText';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, Card, Chip, Field, Header } from '@/components/ui';
import { colors, radius, spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import { kgToPounds, poundsToKg } from '@/utils/health';

type LogType = 'weight' | 'water' | 'mood';
export default function QuickLogScreen() {
  const theme = useTheme(); const { data, logWeight, logWater, logMood } = useApp(); const [type, setType] = useState<LogType>('weight'); const [value, setValue] = useState(''); const [stress, setStress] = useState(2); const units = data.profile?.units ?? 'imperial';
  const save = () => { const amount = Number(value); if (type === 'weight' && amount > 0) logWeight(units === 'imperial' ? poundsToKg(amount) : amount); if (type === 'water' && amount > 0) logWater(amount); if (type === 'mood' && amount >= 1 && amount <= 5) logMood(amount, stress); router.back(); };
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.colors.background }]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Header title="Quick log" subtitle="A few seconds is enough." right={<Pressable accessibilityLabel="Close" onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable>} /><View style={styles.types}><LogChoice icon="scale-outline" label="Weight" selected={type === 'weight'} onPress={() => { setType('weight'); setValue(''); }} /><LogChoice icon="water-outline" label="Water" selected={type === 'water'} onPress={() => { setType('water'); setValue(''); }} /><LogChoice icon="heart-outline" label="Mood" selected={type === 'mood'} onPress={() => { setType('mood'); setValue('3'); }} /></View><Card>{type === 'weight' ? <><Field label={`Weight (${units === 'imperial' ? 'lb' : 'kg'})`} keyboardType="decimal-pad" placeholder={data.weights.at(-1) ? String(Math.round(units === 'imperial' ? kgToPounds(data.weights.at(-1)!.value) : data.weights.at(-1)!.value)) : 'Enter weight'} value={value} onChangeText={setValue} /><Text style={[styles.note, { color: theme.colors.muted }]}>A single entry is information—not a grade.</Text></> : type === 'water' ? <><Field label="Water (milliliters)" keyboardType="number-pad" placeholder="e.g. 2000" value={value} onChangeText={setValue} /><View style={styles.chips}>{[1200, 1800, 2400, 3000].map((item) => <Chip key={item} label={`${item / 1000} L`} selected={Number(value) === item} onPress={() => setValue(String(item))} />)}</View></> : <><Text style={[styles.label, { color: theme.colors.text }]}>Mood</Text><View style={styles.chips}>{[1, 2, 3, 4, 5].map((item) => <Chip key={item} label={`${item}`} selected={Number(value) === item} onPress={() => setValue(String(item))} />)}</View><Text style={[styles.label, { color: theme.colors.text }]}>Stress</Text><View style={styles.chips}>{[1, 2, 3, 4, 5].map((item) => <Chip key={item} label={`${item}`} selected={stress === item} onPress={() => setStress(item)} />)}</View></>}<Button label={`Save ${type}`} icon="checkmark" disabled={!Number(value)} onPress={save} style={styles.save} /></Card>{type === 'mood' ? <Button label="Open full wellness check-in" variant="ghost" onPress={() => { router.back(); router.push('/wellness'); }} /> : null}</ScrollView></SafeAreaView>;
}
function LogChoice({ icon, label, selected, onPress }: { icon: keyof typeof Ionicons.glyphMap; label: string; selected: boolean; onPress: () => void }) { const theme = useTheme(); return <Pressable onPress={onPress} style={[styles.type, { borderColor: selected ? colors.purple : theme.colors.border, backgroundColor: selected ? (theme.isDark ? '#31234F' : '#F1EAFF') : theme.colors.surface }]}><Ionicons name={icon} size={23} color={selected ? colors.purple : theme.colors.muted} /><Text style={[styles.typeLabel, { color: theme.colors.text }]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { width: '100%', maxWidth: 620, alignSelf: 'center', padding: spacing.lg, gap: spacing.lg }, close: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, types: { flexDirection: 'row', gap: 10 }, type: { flex: 1, minHeight: 82, borderWidth: 1, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', gap: 7 }, typeLabel: { fontSize: 12, fontWeight: '900' }, note: { fontSize: 12, lineHeight: 18, marginTop: 10 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 13 }, label: { fontSize: 14, fontWeight: '900', marginTop: 10 }, save: { marginTop: 22 } });
