import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { Text } from '@/components/AppText';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, Card, Chip, Header } from '@/components/ui';
import { colors, radius, spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import type { RecoveryStatus } from '@/types/models';

const triggers = ['Stress', 'Social pressure', 'Anxiety', 'Loneliness', 'Anger', 'Boredom', 'Celebration', 'Relationship issues', 'Work'];
const strategies = ['Call someone', 'Take a walk', 'Exercise', 'Meditation', 'Music', 'Meeting/support group', 'Journal', 'Leave the situation'];
const moods = ['Very difficult', 'Struggling', 'Okay', 'Good', 'Great'];

export default function RecoveryCheckinScreen() {
  const theme = useTheme(); const { saveRecoveryCheckin } = useApp(); const [mood, setMood] = useState(3); const [craving, setCraving] = useState(1); const [status, setStatus] = useState<RecoveryStatus>('met'); const [selectedTriggers, setSelectedTriggers] = useState<string[]>([]); const [selectedStrategies, setSelectedStrategies] = useState<string[]>([]); const [note, setNote] = useState('');
  const toggle = (items: string[], value: string, setter: (next: string[]) => void) => setter(items.includes(value) ? items.filter((item) => item !== value) : [...items, value]);
  const save = () => { saveRecoveryCheckin({ mood, craving, status, triggers: selectedTriggers, strategies: selectedStrategies, note: note.trim() || undefined }); router.back(); };
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.colors.background }]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Header title="Daily recovery check-in" subtitle="Honest, private, and never graded." /><Card><Text style={[styles.label, { color: theme.colors.text }]}>How are you feeling today?</Text><View style={styles.row}>{moods.map((item, index) => <Chip key={item} label={item} selected={mood === index + 1} onPress={() => setMood(index + 1)} />)}</View><Text style={[styles.label, { color: theme.colors.text }]}>How strong are your cravings?</Text><View style={styles.row}>{[1, 2, 3, 4, 5].map((item) => <Chip key={item} label={`${item}`} selected={craving === item} onPress={() => setCraving(item)} />)}</View><Text style={[styles.helper, { color: theme.colors.muted }]}>1 is very low · 5 is very strong</Text></Card><Card><Text style={[styles.label, { color: theme.colors.text }]}>Did you meet your recovery goal today?</Text><View style={styles.row}><Chip label="Goal met" icon="checkmark-circle-outline" selected={status === 'met'} onPress={() => setStatus('met')} /><Chip label="Difficult day" icon="heart-outline" selected={status === 'difficult'} onPress={() => setStatus('difficult')} /><Chip label="Lapse" icon="refresh-outline" selected={status === 'lapse'} onPress={() => setStatus('lapse')} /></View>{status === 'lapse' ? <View style={styles.supportive}><Ionicons name="heart" size={19} color={colors.coral} /><Text style={[styles.supportiveText, { color: theme.colors.text }]}>One difficult day doesn’t erase your progress. Your history and milestones remain.</Text></View> : null}</Card><Card><Text style={[styles.label, { color: theme.colors.text }]}>Was there a trigger?</Text><View style={styles.row}>{triggers.map((item) => <Chip key={item} label={item} selected={selectedTriggers.includes(item)} onPress={() => toggle(selectedTriggers, item, setSelectedTriggers)} />)}</View><Text style={[styles.label, { color: theme.colors.text }]}>What helped today?</Text><View style={styles.row}>{strategies.map((item) => <Chip key={item} label={item} selected={selectedStrategies.includes(item)} onPress={() => toggle(selectedStrategies, item, setSelectedStrategies)} />)}</View></Card><Card><Text style={[styles.label, { color: theme.colors.text }]}>Would you like to write anything down?</Text><TextInput multiline value={note} onChangeText={setNote} placeholder="Private notes, observations, or what you want to remember…" placeholderTextColor={theme.colors.muted} style={[styles.note, { color: theme.colors.text, borderColor: theme.colors.border }]} /></Card><Button label="Save check-in" icon="checkmark" onPress={save} /><Button label="Cancel" variant="ghost" onPress={() => router.back()} /></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { width: '100%', maxWidth: 700, alignSelf: 'center', padding: spacing.lg, paddingBottom: 50, gap: spacing.lg }, label: { fontSize: 15, fontWeight: '600', marginBottom: 11, marginTop: 5 }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 15 }, helper: { fontSize: 11, marginTop: -7 }, supportive: { flexDirection: 'row', gap: 10, padding: 13, backgroundColor: '#B84A5F18', borderRadius: radius.md }, supportiveText: { flex: 1, fontSize: 12, lineHeight: 19, fontWeight: '500' }, note: { minHeight: 124, borderWidth: 1, borderRadius: radius.md, padding: 13, textAlignVertical: 'top', fontSize: 15 } });
