import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, Share, StyleSheet, Switch, View, useWindowDimensions } from 'react-native';
import { Text } from '@/components/AppText';
import { AppScreen, Button, Card, Chip, Header, SectionTitle } from '@/components/ui';
import { colors, radius } from '@/constants/theme';
import { useTheme } from '@/hooks/useTheme';
import { deleteCloudAccount } from '@/services/supabase';
import { useApp } from '@/state/AppProvider';

const dashboardCards = [{ id: 'weight', label: 'Weight' }, { id: 'recovery', label: 'Recovery' }, { id: 'water', label: 'Water' }, { id: 'activity', label: 'Activity' }, { id: 'mood', label: 'Mood' }, { id: 'habits', label: 'Habits' }];

export default function SettingsScreen() {
  const theme = useTheme(); const { width } = useWindowDimensions(); const { data, update, updateSettings, signOut, resetData } = useApp(); const [deleting, setDeleting] = useState(false); const profile = data.profile ?? { firstName: 'Guest', email: 'Not signed in', units: data.onboarding.units };
  const setTheme = (value: 'system' | 'light' | 'dark') => updateSettings({ theme: value });
  const toggleDashboard = (id: string) => updateSettings({ dashboardCards: data.settings.dashboardCards.includes(id) ? data.settings.dashboardCards.filter((item) => item !== id) : [...data.settings.dashboardCards, id] });
  const logout = () => { signOut(); router.replace('/welcome'); };
  const confirmDelete = () => Alert.alert('Delete account and data?', 'This permanently removes local data. If cloud sync is configured, the secure account-deletion function will also be called. This cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete permanently', style: 'destructive', onPress: async () => { setDeleting(true); try { await deleteCloudAccount(); await resetData(); } finally { setDeleting(false); } } }]);
  const themeLabels = { system: 'Use device setting', light: 'Light', dark: 'Dark' } as const;
  return <AppScreen><Header title="Settings" subtitle="Your preferences, privacy, and account." right={<Pressable onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable>} />
    <View style={[styles.columns, width < 780 && styles.stack]}><Card style={styles.flex}><SectionTitle eyebrow="PROFILE" title={profile.firstName} /><Row icon="mail-outline" title="Email" detail={profile.email} /><Row icon="flag-outline" title="Goals" detail={data.onboarding.goals.slice(0, 2).join(', ') || 'Add goals'} /><Row icon="restaurant-outline" title="Diet" detail={data.onboarding.diet || 'No preference saved'} /><Row icon="warning-outline" title="Allergies" detail={data.onboarding.allergies.join(', ') || 'None recorded'} /><Text style={[styles.label, { color: theme.colors.text }]}>Measurement units</Text><View style={styles.chips}><Chip label="Imperial" selected={profile.units === 'imperial'} onPress={() => update((current) => ({ ...current, profile: current.profile ? { ...current.profile, units: 'imperial' } : null, onboarding: { ...current.onboarding, units: 'imperial' } }))} /><Chip label="Metric" selected={profile.units === 'metric'} onPress={() => update((current) => ({ ...current, profile: current.profile ? { ...current.profile, units: 'metric' } : null, onboarding: { ...current.onboarding, units: 'metric' } }))} /></View></Card><Card style={styles.flex}><SectionTitle eyebrow="APPEARANCE" title="Make it comfortable" /><Text style={[styles.label, { color: theme.colors.text }]}>Theme</Text><View style={styles.chips}>{(['system', 'light', 'dark'] as const).map((item) => <Chip key={item} label={themeLabels[item]} selected={data.settings.theme === item} onPress={() => setTheme(item)} />)}</View><Text style={[styles.label, { color: theme.colors.text }]}>Dashboard cards</Text><View style={styles.chips}>{dashboardCards.filter((item) => item.id !== 'recovery' || data.recovery.enabled).map((item) => <Chip key={item.id} label={item.label} selected={data.settings.dashboardCards.includes(item.id)} onPress={() => toggleDashboard(item.id)} />)}</View></Card></View>
    <Card><SectionTitle eyebrow="PRIVACY" title="Sensitive data controls" /><SettingToggle icon="notifications-outline" title="Hide sensitive notification text" detail="Notifications use discreet language on the lock screen." value={data.settings.privateNotifications} onValueChange={(value) => updateSettings({ privateNotifications: value })} /><SettingToggle icon="trophy-outline" title="Milestone notifications" detail="Off by default so celebrations remain private." value={data.settings.milestoneNotifications} onValueChange={(value) => updateSettings({ milestoneNotifications: value })} /><SettingToggle icon="finger-print-outline" title="App PIN / biometric lock" detail="Architecture ready; device enrollment is coming before public beta." value={data.settings.biometricLock} disabled onValueChange={(value) => updateSettings({ biometricLock: value })} badge="Coming before beta" /><SettingToggle icon="shield-checkmark-outline" title="Recovery tracking" detail="Disabling hides Recovery navigation but preserves your history." value={data.recovery.enabled} onValueChange={(value) => update((current) => ({ ...current, recovery: { ...current.recovery, enabled: value } }))} /></Card>
    <Card><SectionTitle eyebrow="YOUR DATA" title="Export and ownership" /><Text style={[styles.body, { color: theme.colors.muted }]}>Export a private JSON snapshot for portability. Treat the shared file as sensitive health data.</Text><Button label="Export my data" variant="secondary" icon="download-outline" onPress={() => Share.share({ title: 'Sober Plus Health data export', message: JSON.stringify({ exportedAt: new Date().toISOString(), formatVersion: 1, data }, null, 2) })} /></Card>
    <Card><SectionTitle eyebrow="ACCOUNT" title="Sign-in and deletion" /><View style={styles.accountButtons}><Button label="Sign out" variant="secondary" icon="log-out-outline" onPress={logout} /><Button label="Delete account and data" variant="danger" icon="trash-outline" loading={deleting} onPress={confirmDelete} /></View><Text style={[styles.deleteNote, { color: theme.colors.muted }]}>Account deletion is intentionally explicit. Production Supabase projects should deploy the included secure delete-account function.</Text></Card>
    <View style={styles.footer}><Text style={[styles.version, { color: theme.colors.muted }]}>Sober Plus Health · MVP 1.0</Text><Text style={[styles.safety, { color: theme.colors.muted }]}>Wellness support, not medical care or emergency treatment.</Text></View>
  </AppScreen>;
}
function Row({ icon, title, detail }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail: string }) { const theme = useTheme(); return <View style={[styles.row, { borderColor: theme.colors.border }]}><Ionicons name={icon} size={19} color={colors.purple} /><View style={styles.flex}><Text style={[styles.rowTitle, { color: theme.colors.text }]}>{title}</Text><Text style={[styles.rowDetail, { color: theme.colors.muted }]}>{detail}</Text></View></View>; }
function SettingToggle({ icon, title, detail, value, onValueChange, disabled, badge }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail: string; value: boolean; onValueChange: (value: boolean) => void; disabled?: boolean; badge?: string }) { const theme = useTheme(); return <View style={[styles.toggle, { borderColor: theme.colors.border }]}><View style={[styles.toggleIcon, { backgroundColor: theme.isDark ? '#29213F' : '#F0E9FF' }]}><Ionicons name={icon} size={19} color={colors.purple} /></View><View style={styles.flex}><View style={styles.titleRow}><Text style={[styles.toggleTitle, { color: theme.colors.text }]}>{title}</Text>{badge ? <Text style={[styles.badge, { backgroundColor: theme.isDark ? '#29213F' : '#F0E9FF' }]}>{badge}</Text> : null}</View><Text style={[styles.rowDetail, { color: theme.colors.muted }]}>{detail}</Text></View><Switch accessibilityLabel={title} disabled={disabled} value={value} onValueChange={onValueChange} trackColor={{ false: theme.colors.strongBorder, true: '#7955D6' }} thumbColor={value ? '#F4F0FF' : theme.colors.surface} /></View>; }
const styles = StyleSheet.create({ close: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' }, columns: { flexDirection: 'row', gap: 16 }, stack: { flexDirection: 'column' }, flex: { flex: 1 }, row: { minHeight: 54, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 11 }, rowTitle: { fontSize: 13, fontWeight: '600' }, rowDetail: { fontSize: 11, lineHeight: 17, marginTop: 2 }, label: { fontSize: 13, fontWeight: '600', marginTop: 18, marginBottom: 9 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, toggle: { minHeight: 72, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 8 }, toggleIcon: { width: 38, height: 38, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, toggleTitle: { fontSize: 14, fontWeight: '600' }, titleRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 7 }, badge: { color: colors.purple, fontSize: 9, fontWeight: '600', paddingHorizontal: 7, paddingVertical: 3, borderRadius: radius.sm }, body: { fontSize: 13, lineHeight: 20, marginBottom: 14 }, accountButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, deleteNote: { fontSize: 11, lineHeight: 17, marginTop: 12 }, footer: { alignItems: 'center', gap: 4 }, version: { fontSize: 12, fontWeight: '600' }, safety: { fontSize: 11 } });
