import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Text } from '@/components/AppText';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, Card, Header, ProgressBar, SectionTitle } from '@/components/ui';
import { colors, radius, spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';

export default function SupportScreen() {
  const theme = useTheme(); const { data } = useApp(); const [seconds, setSeconds] = useState(0); const [breath, setBreath] = useState(0);
  useEffect(() => { if (!seconds) return; const timer = setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [seconds]);
  const phase = ['Breathe in', 'Hold gently', 'Breathe out', 'Pause'][breath % 4];
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.colors.background }]}><ScrollView contentContainerStyle={styles.content}><Header title="You’re not alone" subtitle="Let’s make the next few minutes smaller and safer." right={<Pressable accessibilityLabel="Close support" onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable>} />
    <Card style={styles.breathe}><Text style={styles.kicker}>START HERE</Text><View style={styles.breathCircle}><Ionicons name="leaf" size={31} color="#D8C9FF" /></View><Text style={styles.breathTitle}>{phase}</Text><Text style={styles.breathBody}>Slow and comfortable—there’s no need to force a deep breath.</Text><Button label="Next breath" variant="secondary" onPress={() => setBreath((value) => value + 1)} /></Card>
    <Card><SectionTitle eyebrow="YOUR REASON" title="Reconnect with what matters" /><Text style={[styles.quote, { color: theme.colors.text }]}>“{data.recovery.motivation || data.onboarding.motivation || 'I’m choosing the future I want, one decision at a time.'}”</Text></Card>
    <Card><SectionTitle eyebrow="YOUR PLAN" title="Try one trusted action" /><View style={styles.actions}>{data.recovery.copingStrategies.map((item, index) => <Pressable key={item} onPress={() => item.toLowerCase().includes('call') && data.recovery.trustedContact ? Linking.openURL('tel:') : undefined} style={[styles.action, { borderColor: theme.colors.border }]}><View style={[styles.actionIcon, { backgroundColor: theme.isDark ? '#29213F' : '#F0E9FF' }]}><Ionicons name={['call-outline', 'walk-outline', 'barbell-outline', 'people-outline'][index % 4] as keyof typeof Ionicons.glyphMap} size={19} color={colors.purple} /></View><Text style={[styles.actionText, { color: theme.colors.text }]}>{item}</Text><Ionicons name="chevron-forward" size={18} color={theme.colors.muted} /></Pressable>)}</View></Card>
    <Card><SectionTitle eyebrow="DELAY & REASSESS" title="Give the urge five minutes" />{seconds ? <><Text style={[styles.timer, { color: theme.colors.text }]}>{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, '0')}</Text><ProgressBar value={((300 - seconds) / 300) * 100} detail="Cravings rise and fall. Stay with the next breath, not the whole day." /></> : <><Text style={[styles.body, { color: theme.colors.muted }]}>Start a private timer. When it ends, notice what changed—even slightly.</Text><Button label="Start 5-minute timer" icon="timer-outline" onPress={() => setSeconds(300)} /></>}</Card>
    <Card><SectionTitle eyebrow="PROFESSIONAL SUPPORT" title="Reach a real person" /><Resource icon="chatbubble-ellipses-outline" title="Call or text 988" detail="U.S. Suicide & Crisis Lifeline for mental health or substance-use crisis support" onPress={() => Linking.openURL('tel:988')} /><Resource icon="navigate-outline" title="SAMHSA treatment resources" detail="FindTreatment.gov and the National Helpline: 1-800-662-HELP (4357)" onPress={() => Linking.openURL('https://findtreatment.gov')} /><Resource icon="alert-circle-outline" title="Immediate danger" detail="Call 911 or go to the nearest emergency department." onPress={() => Linking.openURL('tel:911')} /></Card>
    <View style={[styles.warning, { backgroundColor: theme.isDark ? '#332816' : colors.amberSoft }]}><Ionicons name="medical-outline" size={22} color={colors.amber} /><Text style={[styles.warningText, { color: theme.colors.text }]}>Withdrawal from heavy or prolonged alcohol or benzodiazepine use can be dangerous and may require urgent medical care. This app does not provide detox instructions or replace addiction treatment.</Text></View>
    <Button label="I feel steadier—go back" variant="secondary" onPress={() => router.back()} />
  </ScrollView></SafeAreaView>;
}
function Resource({ icon, title, detail, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail: string; onPress: () => void }) { const theme = useTheme(); return <Pressable onPress={onPress} style={[styles.resource, { borderColor: theme.colors.border }]}><Ionicons name={icon} size={23} color={colors.blue} /><View style={styles.flex}><Text style={[styles.resourceTitle, { color: theme.colors.text }]}>{title}</Text><Text style={[styles.detail, { color: theme.colors.muted }]}>{detail}</Text></View><Ionicons name="open-outline" size={17} color={theme.colors.muted} /></Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { width: '100%', maxWidth: 700, alignSelf: 'center', padding: spacing.lg, paddingBottom: 50, gap: spacing.lg }, close: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' }, breathe: { backgroundColor: colors.purple, borderColor: colors.purple, alignItems: 'center' }, kicker: { color: '#D9CCFF', fontSize: 10, fontWeight: '600', letterSpacing: 1.4 }, breathCircle: { width: 98, height: 98, borderRadius: 49, borderWidth: 1, borderColor: '#FFFFFF35', backgroundColor: '#FFFFFF0D', alignItems: 'center', justifyContent: 'center', marginTop: 16 }, breathTitle: { color: colors.white, fontSize: 24, fontWeight: '700', marginTop: 14 }, breathBody: { color: '#E2DBF9', fontSize: 12, textAlign: 'center', lineHeight: 19, marginVertical: 8, maxWidth: 420 }, quote: { fontSize: 19, lineHeight: 29, fontWeight: '600', fontStyle: 'italic' }, actions: { gap: 0 }, action: { minHeight: 56, borderTopWidth: 1, borderRadius: 0, flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 2 }, actionIcon: { width: 36, height: 36, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, actionText: { flex: 1, fontSize: 14, fontWeight: '600' }, timer: { fontSize: 44, fontWeight: '700', textAlign: 'center', letterSpacing: -1.2, marginBottom: 14 }, body: { fontSize: 13, lineHeight: 20, marginBottom: 15 }, resource: { minHeight: 70, borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 10 }, flex: { flex: 1 }, resourceTitle: { fontSize: 14, fontWeight: '600' }, detail: { fontSize: 11, lineHeight: 17, marginTop: 2 }, warning: { borderRadius: radius.md, padding: 14, flexDirection: 'row', gap: 10 }, warningText: { flex: 1, fontSize: 11, lineHeight: 18, fontWeight: '500' } });
