import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View, useWindowDimensions } from 'react-native';
import { Text } from '@/components/AppText';
import { AppScreen, Button, Card, Chip, Header, MiniLineChart, SectionTitle } from '@/components/ui';
import { colors, radius } from '@/constants/theme';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';

const moods = [{ icon: 'rainy-outline' as const, label: 'Very low' }, { icon: 'cloudy-outline' as const, label: 'Low' }, { icon: 'partly-sunny-outline' as const, label: 'Okay' }, { icon: 'sunny-outline' as const, label: 'Good' }, { icon: 'sparkles-outline' as const, label: 'Great' }];

export default function WellnessScreen() {
  const theme = useTheme(); const { width } = useWindowDimensions(); const { data, logMood } = useApp(); const [mood, setMood] = useState(data.moods.at(-1)?.value ?? 3); const [stress, setStress] = useState(data.moods.at(-1)?.stress ?? 2); const [gratitude, setGratitude] = useState(''); const [saved, setSaved] = useState(false); const [breathingSeconds, setBreathingSeconds] = useState(0);
  useEffect(() => { if (!breathingSeconds) return; const timer = setInterval(() => setBreathingSeconds((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [breathingSeconds]);
  const save = () => { logMood(mood, stress); setSaved(true); };
  return <AppScreen><Header title="Wellness" subtitle="A quiet place to notice how you’re doing." right={<Pressable onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable>} />
    <View style={[styles.columns, width < 760 && styles.stack]}><Card style={styles.flex}><SectionTitle eyebrow="DAILY CHECK-IN" title="How are you feeling?" /><View style={styles.moods}>{moods.map((item, index) => <Pressable key={item.label} accessibilityLabel={item.label} accessibilityState={{ selected: mood === index + 1 }} onPress={() => setMood(index + 1)} style={[styles.mood, { borderColor: mood === index + 1 ? colors.purple : theme.colors.border, backgroundColor: mood === index + 1 ? (theme.isDark ? '#312353' : '#F0E9FF') : theme.colors.surface }]}><Ionicons name={item.icon} size={24} color={mood === index + 1 ? colors.purple : theme.colors.muted} /><Text style={[styles.moodText, { color: theme.colors.text }]}>{item.label}</Text></Pressable>)}</View><Text style={[styles.label, { color: theme.colors.text }]}>Stress level</Text><View style={styles.chips}>{[1, 2, 3, 4, 5].map((item) => <Chip key={item} label={`${item}`} selected={stress === item} onPress={() => setStress(item)} />)}</View><Button label={saved ? 'Check-in saved' : 'Save check-in'} icon={saved ? 'checkmark-circle' : 'heart-outline'} onPress={save} /></Card><Card style={styles.flex}><SectionTitle eyebrow="MOOD TREND" title="The last few weeks" /><MiniLineChart values={data.moods.slice(-14).map((item) => item.value)} /><Text style={[styles.observation, { color: theme.colors.text }]}>You often report a better mood on days you exercise.</Text><Text style={[styles.disclaimer, { color: theme.colors.muted }]}>This is a non-causal observation from your logs, not a medical conclusion.</Text></Card></View>
    <View style={[styles.columns, width < 760 && styles.stack]}><Card style={styles.flex}><SectionTitle eyebrow="GRATITUDE" title="One thing worth noticing" /><TextInput multiline value={gratitude} onChangeText={setGratitude} placeholder="Something small is enough…" placeholderTextColor={theme.colors.muted} style={[styles.journal, { color: theme.colors.text, borderColor: theme.colors.border, backgroundColor: theme.colors.surfaceSubtle }]} /><Button label="Save private note" variant="secondary" icon="lock-closed-outline" disabled={!gratitude.trim()} onPress={() => setGratitude('')} /></Card><Card style={styles.flex}><SectionTitle eyebrow="ONE-MINUTE RESET" title="Box breathing" /><View style={[styles.breath, { backgroundColor: theme.isDark ? '#29213F' : '#F1ECFF' }]}><Text style={styles.breathTimer}>{breathingSeconds || <Ionicons name="leaf-outline" size={28} color={colors.purple} />}</Text></View><Text style={[styles.breathCopy, { color: theme.colors.muted }]}>{breathingSeconds ? ['Inhale gently', 'Hold', 'Exhale slowly', 'Pause'][Math.floor((60 - breathingSeconds) / 4) % 4] : 'Inhale 4 · Hold 4 · Exhale 4 · Hold 4'}</Text><Button label={breathingSeconds ? 'Restart one minute' : 'Begin one minute'} variant="secondary" icon="timer-outline" onPress={() => setBreathingSeconds(60)} /></Card></View>
    <Card><View style={styles.note}><Ionicons name="information-circle-outline" size={22} color={colors.blue} /><Text style={[styles.noteText, { color: theme.colors.muted }]}>Mood and stress tracking supports self-awareness. It does not diagnose anxiety, depression, or any mental-health condition. If you are in crisis, call or text 988 in the U.S.</Text></View></Card>
  </AppScreen>;
}
const styles = StyleSheet.create({ close: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' }, columns: { flexDirection: 'row', gap: 16 }, stack: { flexDirection: 'column' }, flex: { flex: 1 }, moods: { flexDirection: 'row', gap: 6, marginBottom: 18 }, mood: { flex: 1, minHeight: 72, borderWidth: 1, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', padding: 5 }, moodText: { fontSize: 9, fontWeight: '600', marginTop: 5, textAlign: 'center' }, label: { fontSize: 13, fontWeight: '600', marginBottom: 9 }, chips: { flexDirection: 'row', gap: 7, marginBottom: 18 }, observation: { fontSize: 13, fontWeight: '600', lineHeight: 20, marginTop: 8 }, disclaimer: { fontSize: 11, lineHeight: 17, marginTop: 4 }, journal: { minHeight: 116, borderWidth: 1, borderRadius: radius.md, padding: 13, textAlignVertical: 'top', marginBottom: 12 }, breath: { alignSelf: 'center', width: 96, height: 96, borderRadius: radius.lg, borderWidth: 1, borderColor: '#9B7AF2', alignItems: 'center', justifyContent: 'center' }, breathTimer: { color: colors.purple, fontSize: 27, fontWeight: '700' }, breathCopy: { textAlign: 'center', marginVertical: 14, fontWeight: '500' }, note: { flexDirection: 'row', gap: 11 }, noteText: { flex: 1, fontSize: 12, lineHeight: 19 } });
