import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { colors, radius, spacing, typeScale } from '@/constants/theme';
import { useTheme } from '@/hooks/useTheme';
import type { RecoveryCheckin, RecoveryStatus } from '@/types/models';
import { dateKey, formatDate } from '@/utils/date';
import { selectionFeedback } from '@/utils/feedback';
import { Text } from './AppText';

const statusCopy: Record<RecoveryStatus, string> = { met: 'Goal met', difficult: 'Difficult day', lapse: 'Lapse recorded', unlogged: 'Not logged' };

export function RecoveryCalendar({ checkins, month = new Date(), onSelect }: { checkins: RecoveryCheckin[]; month?: Date; onSelect?: (checkin: RecoveryCheckin | undefined, date: string) => void }) {
  const theme = useTheme(); const [selectedDate, setSelectedDate] = useState<string | null>(null); const year = month.getFullYear(); const monthIndex = month.getMonth(); const firstDay = new Date(year, monthIndex, 1).getDay(); const days = new Date(year, monthIndex + 1, 0).getDate(); const map = new Map(checkins.map((item) => [item.date, item])); const cells = [...Array.from({ length: firstDay }, () => null), ...Array.from({ length: days }, (_, index) => index + 1)]; const selected = selectedDate ? map.get(selectedDate) : undefined;
  const choose = (key: string) => { selectionFeedback(); setSelectedDate(key); onSelect?.(map.get(key), key); };
  return <View><View style={styles.weekdays}>{['S', 'M', 'T', 'W', 'T', 'F', 'S'].map((day, index) => <Text key={`${day}-${index}`} style={[styles.weekday, { color: theme.colors.faint }]}>{day}</Text>)}</View><View style={styles.grid}>{cells.map((day, index) => { if (!day) return <View key={`blank-${index}`} style={styles.cell} />; const key = dateKey(new Date(year, monthIndex, day)); const checkin = map.get(key); const status = checkin?.status; const statusColor = getStatusColor(status, theme.colors.border); const selectedDay = selectedDate === key; return <View key={key} style={styles.cell}><Pressable accessibilityLabel={`${key}: ${statusCopy[status ?? 'unlogged']}`} accessibilityState={{ selected: selectedDay }} onPress={() => choose(key)} style={({ pressed }) => [styles.day, { borderColor: selectedDay ? colors.purple : 'transparent', backgroundColor: selectedDay ? (theme.isDark ? '#2A2340' : '#F2EDFC') : 'transparent' }, pressed && styles.pressed]}><Text style={[styles.dayText, { color: theme.colors.text }]}>{day}</Text><View style={[styles.statusMark, { backgroundColor: statusColor }]}>{status === 'difficult' ? <Ionicons name="heart" size={7} color={colors.white} /> : status === 'lapse' ? <Ionicons name="refresh" size={7} color={colors.white} /> : null}</View></Pressable></View>; })}</View><View style={styles.legend}><Legend color={colors.success} label="Goal met" /><Legend color={colors.amber} label="Difficult" /><Legend color={colors.coral} label="Lapse" /><Legend color={theme.colors.strongBorder} label="Not logged" /></View>{selectedDate ? <View style={[styles.selection, { borderColor: theme.colors.border, backgroundColor: theme.colors.surfaceSubtle }]}><View style={[styles.selectionBar, { backgroundColor: getStatusColor(selected?.status, theme.colors.strongBorder) }]} /><View style={styles.selectionCopy}><Text style={[styles.selectionDate, { color: theme.colors.text }]}>{formatDate(selectedDate, { weekday: 'long', month: 'long', day: 'numeric' })}</Text><Text style={[styles.selectionStatus, { color: theme.colors.muted }]}>{statusCopy[selected?.status ?? 'unlogged']}{selected ? ` · Mood ${selected.mood}/5 · Cravings ${selected.craving}/5` : ''}</Text>{selected?.note ? <Text numberOfLines={2} style={[styles.note, { color: theme.colors.muted }]}>{selected.note}</Text> : null}</View></View> : <Text style={[styles.hint, { color: theme.colors.faint }]}>Tap a date to view its check-in.</Text>}</View>;
}

function getStatusColor(status: RecoveryStatus | undefined, fallback: string) { if (status === 'met') return colors.success; if (status === 'difficult') return colors.amber; if (status === 'lapse') return colors.coral; return fallback; }
function Legend({ color, label }: { color: string; label: string }) { const theme = useTheme(); return <View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: color }]} /><Text style={[styles.legendText, { color: theme.colors.muted }]}>{label}</Text></View>; }

const styles = StyleSheet.create({ weekdays: { flexDirection: 'row', marginBottom: 5 }, weekday: { width: '14.285%', textAlign: 'center', ...typeScale.caption, fontWeight: '600' }, grid: { flexDirection: 'row', flexWrap: 'wrap' }, cell: { width: '14.285%', aspectRatio: 1, padding: 2 }, day: { flex: 1, borderRadius: radius.sm, borderWidth: 1, alignItems: 'center', justifyContent: 'center', gap: 3 }, pressed: { opacity: 0.65 }, dayText: { fontSize: 12, lineHeight: 15, fontWeight: '600' }, statusMark: { width: 10, height: 10, borderRadius: 5, alignItems: 'center', justifyContent: 'center' }, legend: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginTop: 13 }, legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 }, legendDot: { width: 7, height: 7, borderRadius: 4 }, legendText: { ...typeScale.caption }, selection: { borderTopWidth: 1, borderRadius: radius.sm, marginTop: spacing.lg, padding: 12, flexDirection: 'row', gap: 10 }, selectionBar: { width: 3, borderRadius: 2 }, selectionCopy: { flex: 1 }, selectionDate: { ...typeScale.body, fontWeight: '600' }, selectionStatus: { ...typeScale.caption, marginTop: 2 }, note: { ...typeScale.caption, marginTop: 5 }, hint: { ...typeScale.caption, marginTop: spacing.md } });
