import { Ionicons } from '@expo/vector-icons';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, View, useWindowDimensions } from 'react-native';
import { Text } from '@/components/AppText';
import { AppScreen, Button, Card, Chip, EmptyState, Header, ProgressBar, SectionTitle } from '@/components/ui';
import { colors, gradients, radius, spacing } from '@/constants/theme';
import { workouts } from '@/data/catalog';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import { addDays, dateKey, formatDate } from '@/utils/date';
import { LinearGradient } from 'expo-linear-gradient';

const durations = [10, 20, 30, 45, 60];
const categories = ['All', 'Strength', 'Walking', 'Running', 'Mobility', 'Bodyweight'];

export default function FitnessScreen() {
  const { data, logWorkout } = useApp(); const theme = useTheme(); const { width } = useWindowDimensions(); const [duration, setDuration] = useState(20); const [category, setCategory] = useState('All'); const [selectedId, setSelectedId] = useState('full-body-20');
  const available = useMemo(() => workouts.filter((item) => item.duration <= duration + 10).filter((item) => category === 'All' || item.category === category).filter((item) => item.equipment.includes('No equipment') || item.equipment.some((gear) => data.onboarding.equipment.includes(gear))), [duration, category, data.onboarding.equipment]);
  const selected = available.find((item) => item.id === selectedId) ?? available[0] ?? workouts[0]!; const weekly = data.workoutLogs.filter((item) => item.date >= addDays(dateKey(), -6)); const totalMinutes = weekly.reduce((sum, item) => sum + item.minutes, 0);
  return <AppScreen><Header title="Fitness" subtitle="Move in ways that support the life you’re building." />
    <LinearGradient colors={gradients.dark} style={styles.hero}><View style={styles.heroTop}><View><Text style={styles.eyebrow}>TODAY’S WORKOUT</Text><Text style={styles.heroTitle}>{selected.title}</Text><Text style={styles.heroMeta}>{selected.duration} min · {selected.level} · {selected.category}</Text></View><View style={styles.workoutIcon}><Ionicons name="barbell" size={27} color="#C8B5FF" /></View></View><View style={styles.exerciseList}>{selected.exercises.map((item) => <View key={item} style={styles.exercise}><View style={styles.dot} /><Text style={styles.exerciseText}>{item}</Text></View>)}</View><Button label="Complete workout" icon="checkmark-circle" onPress={() => logWorkout({ workoutId: selected.id, title: selected.title, minutes: selected.duration, completed: true })} /></LinearGradient>
    <Card><SectionTitle eyebrow="MAKE IT FIT" title="Choose your workout" /><Text style={[styles.label, { color: theme.colors.text }]}>Time available</Text><View style={styles.chips}>{durations.map((item) => <Chip key={item} label={item === 60 ? '60+ min' : `${item} min`} selected={duration === item} onPress={() => setDuration(item)} />)}</View><Text style={[styles.label, { color: theme.colors.text }]}>Focus</Text><View style={styles.chips}>{categories.map((item) => <Chip key={item} label={item} selected={category === item} onPress={() => setCategory(item)} />)}</View><View style={styles.suggestions}>{available.map((item) => <Pressable key={item.id} onPress={() => setSelectedId(item.id)} style={[styles.suggestion, { borderColor: selected.id === item.id ? colors.purple : theme.colors.border, backgroundColor: selected.id === item.id ? (theme.isDark ? '#2C214C' : '#F5F0FF') : theme.colors.surface }]}><View style={styles.suggestionIcon}><Ionicons name={workoutIcon(item.category)} size={20} color={colors.purple} /></View><View style={styles.flex}><Text style={[styles.suggestionTitle, { color: theme.colors.text }]}>{item.title}</Text><Text style={[styles.meta, { color: theme.colors.muted }]}>{item.duration} min · {item.equipment.join(', ')}</Text></View><Ionicons name={selected.id === item.id ? 'checkmark-circle' : 'chevron-forward'} size={20} color={selected.id === item.id ? colors.purple : theme.colors.muted} /></Pressable>)}</View></Card>
    <View style={[styles.columns, width < 760 && styles.stack]}><Card style={styles.flex}><SectionTitle eyebrow="THIS WEEK" title="Your rhythm" /><View style={styles.stats}><View><Text style={[styles.stat, { color: theme.colors.text }]}>{weekly.length}</Text><Text style={[styles.meta, { color: theme.colors.muted }]}>workouts</Text></View><View><Text style={[styles.stat, { color: theme.colors.text }]}>{totalMinutes}</Text><Text style={[styles.meta, { color: theme.colors.muted }]}>active minutes</Text></View></View><ProgressBar value={(weekly.length / 4) * 100} label="Weekly goal" detail={`${Math.max(4 - weekly.length, 0)} workouts left—short sessions count.`} /></Card><Card style={styles.flex}><SectionTitle eyebrow="RECENT" title="Workout history" />{data.workoutLogs.length ? data.workoutLogs.slice(-4).reverse().map((item) => <View key={item.id} style={[styles.history, { borderColor: theme.colors.border }]}><View style={styles.historyCheck}><Ionicons name="checkmark" size={15} color={colors.success} /></View><View style={styles.flex}><Text style={[styles.historyTitle, { color: theme.colors.text }]}>{item.title}</Text><Text style={[styles.meta, { color: theme.colors.muted }]}>{formatDate(item.date)} · {item.minutes} min</Text></View></View>) : <EmptyState icon="barbell-outline" title="No workouts logged yet" body="Your first one can start today." />}</Card></View>
    <Card><View style={styles.info}><Ionicons name="leaf-outline" size={21} color={colors.success} /><View style={styles.flex}><Text style={[styles.infoTitle, { color: theme.colors.text }]}>Beginner-friendly by design</Text><Text style={[styles.meta, { color: theme.colors.muted }]}>Adjust pace, range of motion, and rest to your body. Stop if you feel sharp pain, dizziness, or unusual symptoms.</Text></View></View></Card>
  </AppScreen>;
}

function workoutIcon(category: string): keyof typeof Ionicons.glyphMap { if (category === 'Walking' || category === 'Running') return 'walk-outline'; if (category === 'Mobility') return 'body-outline'; return 'barbell-outline'; }
const styles = StyleSheet.create({ hero: { borderRadius: radius.lg, padding: spacing.xl }, heroTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 16 }, eyebrow: { color: '#9F98B8', fontSize: 10, fontWeight: '600', letterSpacing: 1.5 }, heroTitle: { color: colors.white, fontSize: 25, lineHeight: 31, fontWeight: '700', marginTop: 5 }, heroMeta: { color: '#B8B4C9', marginTop: 4 }, workoutIcon: { width: 46, height: 46, borderRadius: radius.md, backgroundColor: '#FFFFFF0D', alignItems: 'center', justifyContent: 'center' }, exerciseList: { gap: 10, marginVertical: 20 }, exercise: { flexDirection: 'row', alignItems: 'center', gap: 10 }, dot: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#9B7BFF' }, exerciseText: { color: '#E8E5F1', fontSize: 14 }, label: { fontSize: 13, fontWeight: '600', marginBottom: 9, marginTop: 4 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 18 }, suggestions: { gap: 0 }, suggestion: { minHeight: 64, borderTopWidth: 1, borderRadius: 0, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 12 }, suggestionIcon: { width: 36, height: 36, borderRadius: radius.md, backgroundColor: '#6D3EEB18', alignItems: 'center', justifyContent: 'center' }, suggestionTitle: { fontSize: 14, fontWeight: '600' }, flex: { flex: 1 }, meta: { fontSize: 12, lineHeight: 18, marginTop: 2 }, columns: { flexDirection: 'row', gap: 16 }, stack: { flexDirection: 'column' }, stats: { flexDirection: 'row', gap: 48, marginBottom: 20 }, stat: { fontSize: 30, lineHeight: 36, fontWeight: '700' }, history: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: 1 }, historyCheck: { width: 26, height: 26, borderRadius: radius.sm, backgroundColor: '#16836B18', alignItems: 'center', justifyContent: 'center' }, historyTitle: { fontSize: 14, fontWeight: '600' }, info: { flexDirection: 'row', gap: 13 }, infoTitle: { fontSize: 15, fontWeight: '600' } });
