import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useDeferredValue, useMemo, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View, useWindowDimensions } from 'react-native';
import { Text } from '@/components/AppText';
import { NutritionNav, RecipeCard, RecipeImage } from '@/components/NutritionUI';
import { AppScreen, Button, Chip, EmptyState, Header, SectionTitle } from '@/components/ui';
import { colors, radius, typeScale } from '@/constants/theme';
import { meals } from '@/data/catalog';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import { filterMeals } from '@/utils/nutrition';

const filters = ['All', 'Breakfast', 'Lunch', 'Dinner', 'Snack', 'High Protein', 'Weight Loss', 'Muscle Gain', 'Weight Gain', 'Vegetarian', 'Vegan', 'Quick Meals', 'Budget Friendly', 'Meal Prep'];

export default function NutritionScreen() {
  const theme = useTheme(); const { width } = useWindowDimensions(); const { data, toggleSavedMeal, logMeal } = useApp(); const [filter, setFilter] = useState('All'); const [search, setSearch] = useState(''); const [swapOffset, setSwapOffset] = useState(0); const deferredSearch = useDeferredValue(search.trim().toLowerCase());
  const recommendations = useMemo(() => filterMeals(meals.filter((mealItem) => !data.dislikedMeals.includes(mealItem.id)), data.onboarding, filter, data.savedMeals).filter((mealItem) => !deferredSearch || [mealItem.title, mealItem.description, mealItem.cuisine ?? '', ...mealItem.tags, ...mealItem.ingredients.map((ingredient) => ingredient.name)].join(' ').toLowerCase().includes(deferredSearch)), [data.dislikedMeals, data.onboarding, data.savedMeals, deferredSearch, filter]);
  const arranged = recommendations.length ? [...recommendations.slice(swapOffset), ...recommendations.slice(0, swapOffset)] : []; const wide = width >= 760; const featured = arranged[0];
  return <AppScreen><Header title="Nutrition" subtitle="Food you already enjoy, organized around your goals." />
    <NutritionNav current="recipes" />
    <View style={[styles.preferenceLine, { borderColor: theme.colors.border }]}><Ionicons name="sparkles-outline" size={18} color={colors.purple} /><Text style={[styles.preferenceText, { color: theme.colors.muted }]}>Prioritized for {data.onboarding.goals.slice(0, 2).join(' and ').toLowerCase() || 'balanced variety'}{data.savedMeals.length ? ' and the foods you save' : ''} · {data.onboarding.allergies.length ? `excluding ${data.onboarding.allergies.join(', ')}` : 'no allergens recorded'}</Text></View>
    <View style={styles.quickActions}><QuickAction icon="layers-outline" title="Build your own bowl" detail="Choose every ingredient" onPress={() => router.push('/build-bowl')} /><QuickAction icon="calendar-outline" title="Plan the week" detail={`${data.mealPlan.length} meal${data.mealPlan.length === 1 ? '' : 's'} planned`} onPress={() => router.push('/meal-plan')} /><QuickAction icon="basket-outline" title="Grocery list" detail={`${data.groceryItems.length} item${data.groceryItems.length === 1 ? '' : 's'}`} onPress={() => router.push('/grocery-list')} /></View>
    <View style={[styles.search, { backgroundColor: theme.colors.surface, borderColor: theme.colors.strongBorder }]}><Ionicons name="search" size={18} color={theme.colors.faint} /><TextInput accessibilityLabel="Search recipes and ingredients" value={search} onChangeText={setSearch} placeholder="Search chicken, rice, Mexican, pasta…" placeholderTextColor={theme.colors.faint} style={[styles.searchInput, { color: theme.colors.text }]} /></View>
    <View style={styles.filters}>{filters.map((item) => <Chip key={item} label={item} selected={filter === item} onPress={() => { setFilter(item); setSwapOffset(0); }} />)}</View>
    {featured ? <View style={[styles.featured, { borderColor: theme.colors.border, backgroundColor: theme.colors.surface }]}><Pressable accessibilityLabel={`Open featured recipe ${featured.title}`} onPress={() => router.push(`/recipe/${featured.id}` as never)}><RecipeImage meal={featured} height={wide ? 230 : 190} /></Pressable><View style={[styles.featuredBody, !wide && styles.featuredMobile]}><View style={styles.featuredCopy}><View style={styles.featuredTop}><Text style={styles.eyebrow}>FEATURED FOR YOU</Text><Pressable onPress={() => setSwapOffset((value) => (value + 1) % recommendations.length)} style={styles.swap}><Ionicons name="refresh" size={16} color={colors.purple} /><Text style={styles.swapText}>Swap</Text></Pressable></View><Text style={[styles.featuredTitle, { color: theme.colors.text }]}>{featured.title}</Text><Text style={[styles.description, { color: theme.colors.muted }]}>{featured.description}</Text><View style={styles.metaRow}><Text style={[styles.metaStrong, { color: theme.colors.text }]}>{featured.protein}g protein</Text><Text style={[styles.meta, { color: theme.colors.faint }]}>{featured.calories} cal · {featured.time} min</Text></View></View><View style={styles.featuredActions}><Button label="View recipe" icon="arrow-forward" onPress={() => router.push(`/recipe/${featured.id}` as never)} /><Button label={data.savedMeals.includes(featured.id) ? 'Saved' : 'Save'} icon={data.savedMeals.includes(featured.id) ? 'heart' : 'heart-outline'} variant="secondary" onPress={() => toggleSavedMeal(featured.id)} /><Pressable accessibilityRole="button" onPress={() => logMeal(featured.id)}><Text style={styles.logAction}>Log this meal</Text></Pressable></View></View></View> : null}
    <View><SectionTitle eyebrow="RECIPE COLLECTION" title={`${arranged.length} meals match`} />{arranged.length ? <View style={styles.mealGrid}>{arranged.map((mealItem) => <RecipeCard key={mealItem.id} meal={mealItem} saved={data.savedMeals.includes(mealItem.id)} onSave={() => toggleSavedMeal(mealItem.id)} />)}</View> : <EmptyState icon="search-outline" title="No matching meals" body="Try another search or filter. Your allergy and diet preferences remain active." />}</View>
    <View style={[styles.notice, { borderColor: theme.colors.border }]}><Ionicons name="information-circle-outline" size={20} color={colors.blue} /><Text style={[styles.description, styles.flex, { color: theme.colors.muted }]}>Nutrition estimates are general wellness information, not medical nutrition therapy. Individual needs may vary.</Text></View>
  </AppScreen>;
}

function QuickAction({ icon, title, detail, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail: string; onPress: () => void }) { const theme = useTheme(); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.quickAction, { borderColor: theme.colors.border, backgroundColor: theme.colors.surface }, pressed && styles.pressed]}><Ionicons name={icon} size={20} color={colors.purple} /><View style={styles.flex}><Text style={[styles.quickTitle, { color: theme.colors.text }]}>{title}</Text><Text style={[styles.quickDetail, { color: theme.colors.muted }]}>{detail}</Text></View><Ionicons name="chevron-forward" size={17} color={theme.colors.faint} /></Pressable>; }

const styles = StyleSheet.create({ preferenceLine: { borderBottomWidth: 1, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 8 }, preferenceText: { ...typeScale.label, flex: 1 }, quickActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, quickAction: { flexGrow: 1, flexBasis: 210, minHeight: 66, borderWidth: 1, borderRadius: radius.md, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10 }, quickTitle: { ...typeScale.body, fontWeight: '600' }, quickDetail: { ...typeScale.caption, marginTop: 1 }, search: { minHeight: 48, borderWidth: 1, borderRadius: radius.md, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, gap: 9 }, searchInput: { flex: 1, fontSize: 15, outlineStyle: 'none' } as never, filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, featured: { borderWidth: 1, borderRadius: radius.lg, overflow: 'hidden' }, featuredTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: colors.purple, ...typeScale.caption, fontWeight: '600', letterSpacing: 1.3 }, swap: { flexDirection: 'row', alignItems: 'center', gap: 5, padding: 7 }, swapText: { color: colors.purple, ...typeScale.label, fontWeight: '600' }, featuredBody: { flexDirection: 'row', alignItems: 'flex-end', gap: 22, padding: 18 }, featuredMobile: { flexDirection: 'column', alignItems: 'stretch' }, featuredCopy: { flex: 1 }, featuredTitle: { fontSize: 24, lineHeight: 30, fontWeight: '700', marginTop: 3 }, description: { ...typeScale.body, marginTop: 4 }, featuredActions: { minWidth: 150, gap: 7 }, metaRow: { flexDirection: 'row', alignItems: 'center', gap: 13, marginTop: 11 }, metaStrong: { ...typeScale.label, fontWeight: '600' }, meta: { ...typeScale.label }, logAction: { color: colors.purple, ...typeScale.label, fontWeight: '600', textAlign: 'center', padding: 8 }, mealGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 }, notice: { borderTopWidth: 1, paddingTop: 16, flexDirection: 'row', gap: 11 }, flex: { flex: 1 }, pressed: { opacity: .76 } });
