import { Ionicons } from '@expo/vector-icons';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View, useWindowDimensions } from 'react-native';
import { Text } from '@/components/AppText';
import { AppScreen, Button, Card, Chip, EmptyState, Header, SectionTitle } from '@/components/ui';
import { colors, radius, typeScale } from '@/constants/theme';
import { meals } from '@/data/catalog';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import type { Meal } from '@/types/models';
import { filterMeals } from '@/utils/nutrition';

const filters = ['All', 'Breakfast', 'Lunch', 'Dinner', 'Snack', 'High-protein', 'Vegetarian', 'Vegan', 'Quick meals', 'Budget meals'];

export default function NutritionScreen() {
  const theme = useTheme(); const { width } = useWindowDimensions(); const { data, toggleSavedMeal, dislikeMeal, logMeal } = useApp(); const [filter, setFilter] = useState('All'); const [search, setSearch] = useState(''); const [swapOffset, setSwapOffset] = useState(0);
  const recommendations = useMemo(() => filterMeals(meals.filter((meal) => !data.dislikedMeals.includes(meal.id)), data.onboarding, filter).filter((meal) => !search || `${meal.title} ${meal.ingredients.join(' ')}`.toLowerCase().includes(search.toLowerCase())), [data.onboarding, data.dislikedMeals, filter, search]);
  const arranged = recommendations.length ? [...recommendations.slice(swapOffset), ...recommendations.slice(0, swapOffset)] : []; const wide = width >= 760; const featured = arranged[0];
  return <AppScreen><Header title="Nutrition" subtitle="Useful food ideas, filtered around your preferences." />
    <View style={[styles.preferenceLine, { borderColor: theme.colors.border }]}><Ionicons name="shield-checkmark-outline" size={18} color={colors.success} /><Text style={[styles.preferenceText, { color: theme.colors.muted }]}>Personalized for {data.onboarding.goals.slice(0, 2).join(' and ').toLowerCase() || 'your goals'} · {data.onboarding.allergies.length ? `excluding ${data.onboarding.allergies.join(', ')}` : 'no allergens recorded'}</Text></View>
    <View style={[styles.search, { backgroundColor: theme.colors.surface, borderColor: theme.colors.strongBorder }]}><Ionicons name="search" size={18} color={theme.colors.faint} /><TextInput accessibilityLabel="Search foods and meals" value={search} onChangeText={setSearch} placeholder="Search foods or meals" placeholderTextColor={theme.colors.faint} style={[styles.searchInput, { color: theme.colors.text }]} /></View>
    <View style={styles.filters}>{filters.map((item) => <Chip key={item} label={item} selected={filter === item} onPress={() => { setFilter(item); setSwapOffset(0); }} />)}</View>
    {featured ? <View style={[styles.featured, { borderColor: theme.colors.border, backgroundColor: theme.colors.surface }]}><View style={styles.featuredTop}><Text style={styles.eyebrow}>FEATURED FOR YOU</Text><Pressable onPress={() => setSwapOffset((value) => (value + 1) % recommendations.length)} style={styles.swap}><Ionicons name="refresh" size={16} color={colors.purple} /><Text style={styles.swapText}>Swap</Text></Pressable></View><View style={[styles.featuredBody, !wide && styles.featuredMobile]}><View style={styles.featuredCopy}><Text style={[styles.featuredTitle, { color: theme.colors.text }]}>{featured.title}</Text><Text style={[styles.description, { color: theme.colors.muted }]}>{featured.description}</Text><View style={styles.metaRow}><Text style={[styles.metaStrong, { color: theme.colors.text }]}>{featured.protein}g protein</Text><Text style={[styles.meta, { color: theme.colors.faint }]}>{featured.time} min · {featured.category}</Text></View></View><View style={styles.featuredActions}><Button label="Mark eaten" icon="checkmark" onPress={() => logMeal(featured.id)} /><Button label={data.savedMeals.includes(featured.id) ? 'Saved' : 'Save'} icon={data.savedMeals.includes(featured.id) ? 'bookmark' : 'bookmark-outline'} variant="secondary" onPress={() => toggleSavedMeal(featured.id)} /></View></View></View> : null}
    <View><SectionTitle eyebrow="MORE IDEAS" title={`${Math.max(0, arranged.length - 1)} meals match`} />{arranged.length > 1 ? <View style={styles.mealGrid}>{arranged.slice(1, 9).map((meal) => <View key={meal.id} style={[styles.mealItem, { borderColor: theme.colors.border }, wide && styles.mealWide]}><MealRow meal={meal} saved={data.savedMeals.includes(meal.id)} onSave={() => toggleSavedMeal(meal.id)} onDislike={() => dislikeMeal(meal.id)} onLog={() => logMeal(meal.id)} /></View>)}</View> : !featured ? <EmptyState icon="search-outline" title="No matching meals" body="Try another filter or update your food preferences. Allergies remain excluded." /> : null}</View>
    <Card><View style={styles.notice}><Ionicons name="information-circle-outline" size={20} color={colors.blue} /><View style={styles.flex}><Text style={[styles.noticeTitle, { color: theme.colors.text }]}>General wellness information</Text><Text style={[styles.description, { color: theme.colors.muted }]}>These ideas are not medical nutrition therapy and never use extreme calorie restriction. Individualized medical needs should be discussed with a qualified healthcare professional.</Text></View></View></Card>
  </AppScreen>;
}

function MealRow({ meal, saved, onSave, onDislike, onLog }: { meal: Meal; saved: boolean; onSave: () => void; onDislike: () => void; onLog: () => void }) { const theme = useTheme(); return <><View style={styles.mealHeader}><View><Text style={styles.category}>{meal.category.toUpperCase()}</Text><Text style={[styles.mealTitle, { color: theme.colors.text }]}>{meal.title}</Text></View><Pressable accessibilityLabel={`${saved ? 'Remove' : 'Save'} ${meal.title}`} onPress={onSave} style={styles.iconButton}><Ionicons name={saved ? 'bookmark' : 'bookmark-outline'} size={18} color={saved ? colors.purple : theme.colors.faint} /></Pressable></View><Text style={[styles.description, { color: theme.colors.muted }]}>{meal.description}</Text><View style={styles.metaRow}><Text style={[styles.metaStrong, { color: theme.colors.text }]}>{meal.protein}g protein</Text><Text style={[styles.meta, { color: theme.colors.faint }]}>{meal.time} min</Text></View><View style={styles.rowActions}><Pressable onPress={onLog}><Text style={styles.actionText}>Mark eaten</Text></Pressable><Pressable accessibilityLabel={`Dislike ${meal.title}`} onPress={onDislike}><Text style={[styles.secondaryAction, { color: theme.colors.faint }]}>Not for me</Text></Pressable></View></>; }

const styles = StyleSheet.create({ preferenceLine: { borderTopWidth: 1, borderBottomWidth: 1, paddingVertical: 11, flexDirection: 'row', alignItems: 'center', gap: 8 }, preferenceText: { ...typeScale.label, flex: 1 }, search: { minHeight: 48, borderWidth: 1, borderRadius: radius.md, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, gap: 9 }, searchInput: { flex: 1, fontSize: 15, outlineStyle: 'none' } as never, filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, featured: { borderTopWidth: 1, borderBottomWidth: 1, paddingVertical: 18, paddingHorizontal: 2 }, featuredTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: colors.purple, ...typeScale.caption, fontWeight: '600', letterSpacing: 1.3 }, swap: { flexDirection: 'row', alignItems: 'center', gap: 5, padding: 7 }, swapText: { color: colors.purple, ...typeScale.label, fontWeight: '600' }, featuredBody: { flexDirection: 'row', alignItems: 'flex-end', gap: 22, marginTop: 10 }, featuredMobile: { flexDirection: 'column', alignItems: 'stretch' }, featuredCopy: { flex: 1 }, featuredTitle: { fontSize: 24, lineHeight: 30, fontWeight: '700' }, description: { ...typeScale.body, marginTop: 4 }, featuredActions: { minWidth: 145, gap: 7 }, metaRow: { flexDirection: 'row', alignItems: 'center', gap: 13, marginTop: 11 }, metaStrong: { ...typeScale.label, fontWeight: '600' }, meta: { ...typeScale.label }, mealGrid: { flexDirection: 'row', flexWrap: 'wrap', columnGap: 24 }, mealItem: { width: '100%', borderTopWidth: 1, paddingVertical: 17 }, mealWide: { width: '48%' }, mealHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, category: { color: colors.purple, ...typeScale.caption, fontWeight: '600', letterSpacing: 1 }, mealTitle: { ...typeScale.bodyLarge, fontWeight: '700', marginTop: 3 }, iconButton: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' }, rowActions: { flexDirection: 'row', gap: 17, marginTop: 13 }, actionText: { color: colors.purple, ...typeScale.label, fontWeight: '600' }, secondaryAction: { ...typeScale.label, fontWeight: '500' }, notice: { flexDirection: 'row', gap: 11 }, noticeTitle: { ...typeScale.body, fontWeight: '600' }, flex: { flex: 1 } });
