import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, View, useWindowDimensions } from 'react-native';
import { Text } from '@/components/AppText';
import { AppScreen, Card, Header, MiniLineChart, ProgressBar, SectionTitle } from '@/components/ui';
import { colors, radius, typeScale } from '@/constants/theme';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import { addDays, dateKey, formatDate } from '@/utils/date';
import { calculateBmi, kgToPounds, weightTrend } from '@/utils/health';
import { recoveryStats } from '@/utils/recovery';
import { selectionFeedback } from '@/utils/feedback';

const ranges = [{ label: '7D', days: 7 }, { label: '30D', days: 30 }, { label: '3M', days: 90 }, { label: '6M', days: 180 }, { label: '1Y', days: 365 }];

export default function ProgressScreen() {
  const theme = useTheme(); const { width } = useWindowDimensions(); const { data } = useApp(); const [range, setRange] = useState(ranges[1]!); const cutoff = addDays(dateKey(), -range.days); const weights = data.weights.filter((item) => item.date >= cutoff); const moods = data.moods.filter((item) => item.date >= cutoff); const water = data.water.filter((item) => item.date >= cutoff); const workouts = data.workoutLogs.filter((item) => item.date >= cutoff); const rec = recoveryStats(data.recovery.startDate, data.recoveryCheckins); const trend = weightTrend(weights); const units = data.profile?.units ?? 'imperial'; const wide = width >= 760; const labels = (entries: { date: string }[]) => entries.map((item) => formatDate(item.date));
  return <AppScreen><Header title="Progress" subtitle="Patterns and milestones across your health." right={<Pressable accessibilityRole="button" onPress={() => router.push('/wellness')} style={[styles.wellnessLink, { borderColor: theme.colors.strongBorder }]}><Ionicons name="heart-outline" size={17} color={colors.purple} /><Text style={[styles.wellnessText, { color: theme.colors.text }]}>Wellness</Text></Pressable>} />
    <View style={[styles.rangeControl, { borderColor: theme.colors.border, backgroundColor: theme.colors.surfaceSubtle }]}>{ranges.map((item) => <Pressable key={item.label} onPress={() => { selectionFeedback(); setRange(item); }} style={[styles.rangeButton, range.label === item.label && { backgroundColor: theme.colors.surface, borderColor: theme.colors.strongBorder }]}><Text style={[styles.rangeLabel, { color: range.label === item.label ? theme.colors.text : theme.colors.muted }]}>{item.label}</Text></Pressable>)}</View>
    <View style={[styles.summary, { borderColor: theme.colors.border }]}><SummaryItem label="Weight change" value={`${trend > 0 ? '+' : ''}${(units === 'imperial' ? kgToPounds(trend) : trend).toFixed(1)} ${units === 'imperial' ? 'lb' : 'kg'}`} detail="No judgment—just context" /><SummaryItem label="Training" value={`${workouts.length}`} detail={`${workouts.reduce((sum, item) => sum + item.minutes, 0)} active minutes`} /><SummaryItem label="Mood average" value={moods.length ? `${(moods.reduce((sum, item) => sum + item.value, 0) / moods.length).toFixed(1)} / 5` : '—'} detail={`${moods.length} logged days`} />{data.recovery.enabled ? <SummaryItem label="Current streak" value={`${rec.currentStreak} days`} detail={`${rec.totalMet} goal-met check-ins`} /> : null}</View>

    <View style={[styles.grid, !wide && styles.stack]}><Card style={styles.chartCard}><SectionTitle eyebrow="BODY" title="Weight trend" /><MiniLineChart values={weights.map((item) => units === 'imperial' ? kgToPounds(item.value) : item.value)} labels={labels(weights)} /><ChartFooter left={weights.length ? `${(units === 'imperial' ? kgToPounds(weights[0]!.value) : weights[0]!.value).toFixed(1)}` : 'No entries'} right={weights.length ? `${(units === 'imperial' ? kgToPounds(weights.at(-1)!.value) : weights.at(-1)!.value).toFixed(1)} ${units === 'imperial' ? 'lb' : 'kg'}` : ''} /></Card><Card style={styles.chartCard}><SectionTitle eyebrow="WELLNESS" title="Mood trend" /><MiniLineChart values={moods.map((item) => item.value)} labels={labels(moods)} /><ChartFooter left="1 · very low" right="5 · great" /></Card></View>
    <View style={[styles.grid, !wide && styles.stack]}><Card style={styles.chartCard}><SectionTitle eyebrow="TRAINING" title="Workout duration" /><MiniLineChart values={workouts.map((item) => item.minutes)} labels={labels(workouts)} /><Text style={[styles.insight, { color: theme.colors.text }]}>{data.workoutLogs.length} total workouts completed</Text><Text style={[styles.supporting, { color: theme.colors.muted }]}>Short sessions count toward consistency.</Text></Card><Card style={styles.chartCard}><SectionTitle eyebrow="HYDRATION" title="Water intake" /><MiniLineChart values={water.map((item) => item.value / 1000)} labels={labels(water)} /><ProgressBar value={water.length ? (water.at(-1)!.value / 2400) * 100 : 0} label="Latest day" detail="Compared with your 2.4 L goal." /></Card></View>
    <View style={[styles.grid, !wide && styles.stack]}><Card style={styles.chartCard}><SectionTitle eyebrow="SCREENING CONTEXT" title="BMI trend" /><MiniLineChart values={weights.map((item) => calculateBmi(item.value, data.profile?.heightCm ?? 0) ?? 0)} labels={labels(weights)} /><Text style={[styles.disclaimer, { color: theme.colors.muted }]}>BMI does not measure body composition or distinguish muscle from fat. Performance, strength, energy, and long-term trends may be more useful.</Text></Card>{data.recovery.enabled ? <Card style={styles.chartCard}><SectionTitle eyebrow="RECOVERY" title="Goal-met days" /><View style={styles.recoveryStat}><Text style={[styles.recoveryNumber, { color: theme.colors.text }]}>{rec.totalMet}</Text><Text style={[styles.recoveryCopy, { color: theme.colors.muted }]}>days logged as goal met or difficult—but protected</Text></View><ProgressBar value={rec.consistency} label="Check-in consistency" detail={`${Math.round(rec.successRate)}% of logged days met your goal.`} /></Card> : null}</View>
    <View style={styles.milestones}><SectionTitle eyebrow="MILESTONES" title="Wins worth noticing" />{data.achievements.map((achievement) => <View key={achievement.id} style={[styles.milestone, { borderColor: theme.colors.border }]}><View style={[styles.milestoneMark, { backgroundColor: achievement.earnedAt ? colors.purple : theme.colors.strongBorder }]} /><View style={styles.flex}><Text style={[styles.milestoneTitle, { color: theme.colors.text }]}>{achievement.title}</Text><Text style={[styles.supporting, { color: theme.colors.muted }]}>{achievement.earnedAt ? achievement.detail : 'In progress'}</Text></View><Text style={[styles.milestoneState, { color: achievement.earnedAt ? colors.purple : theme.colors.faint }]}>{achievement.earnedAt ? 'Earned' : 'Open'}</Text></View>)}</View>
  </AppScreen>;
}

function SummaryItem({ label, value, detail }: { label: string; value: string; detail: string }) { const theme = useTheme(); return <View style={styles.summaryItem}><Text style={[styles.summaryLabel, { color: theme.colors.muted }]}>{label}</Text><Text style={[styles.summaryValue, { color: theme.colors.text }]}>{value}</Text><Text style={[styles.supporting, { color: theme.colors.faint }]}>{detail}</Text></View>; }
function ChartFooter({ left, right }: { left: string; right: string }) { const theme = useTheme(); return <View style={styles.chartFooter}><Text style={[styles.chartLabel, { color: theme.colors.faint }]}>{left}</Text><Text style={[styles.chartLabel, { color: theme.colors.faint }]}>{right}</Text></View>; }

const styles = StyleSheet.create({ wellnessLink: { minHeight: 38, borderWidth: 1, borderRadius: radius.md, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 6 }, wellnessText: { ...typeScale.label, fontWeight: '600' }, rangeControl: { flexDirection: 'row', alignSelf: 'flex-start', borderWidth: 1, borderRadius: radius.md, padding: 3, gap: 2 }, rangeButton: { minWidth: 46, minHeight: 34, borderRadius: radius.sm, borderWidth: 1, borderColor: 'transparent', alignItems: 'center', justifyContent: 'center' }, rangeLabel: { ...typeScale.label, fontWeight: '600' }, summary: { flexDirection: 'row', flexWrap: 'wrap', borderTopWidth: 1, borderBottomWidth: 1, paddingVertical: 18, gap: 24 }, summaryItem: { flex: 1, minWidth: 140 }, summaryLabel: { ...typeScale.label, fontWeight: '500' }, summaryValue: { fontSize: 24, lineHeight: 30, fontWeight: '700', marginTop: 4 }, supporting: { ...typeScale.caption, marginTop: 2 }, grid: { flexDirection: 'row', gap: 16 }, stack: { flexDirection: 'column' }, chartCard: { flex: 1, minWidth: 0 }, chartFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 7 }, chartLabel: { ...typeScale.caption, fontWeight: '500' }, insight: { ...typeScale.body, fontWeight: '600', marginTop: 10 }, disclaimer: { ...typeScale.caption, marginTop: 10 }, recoveryStat: { flexDirection: 'row', alignItems: 'baseline', gap: 10, marginBottom: 20 }, recoveryNumber: { fontSize: 44, lineHeight: 50, fontWeight: '700' }, recoveryCopy: { ...typeScale.body, flex: 1 }, milestones: { marginTop: 2 }, milestone: { minHeight: 60, borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 11 }, milestoneMark: { width: 8, height: 8, borderRadius: 4 }, milestoneTitle: { ...typeScale.body, fontWeight: '600' }, milestoneState: { ...typeScale.label, fontWeight: '600' }, flex: { flex: 1 } });
