import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { Pressable, StyleSheet, View, useWindowDimensions } from 'react-native';
import { Text } from '@/components/AppText';
import { RecoveryCalendar } from '@/components/RecoveryCalendar';
import { AppScreen, Button, Card, Header, ProgressBar, SectionTitle } from '@/components/ui';
import { colors, gradients, radius, spacing, typeScale } from '@/constants/theme';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import { dateKey, formatDate } from '@/utils/date';
import { recoveryStats } from '@/utils/recovery';

export default function RecoveryScreen() {
  const { data } = useApp(); const theme = useTheme(); const { width } = useWindowDimensions(); const stats = recoveryStats(data.recovery.startDate, data.recoveryCheckins); const todayCheck = data.recoveryCheckins.find((item) => item.date === dateKey()); const currentMonth = new Date(); const wide = width >= 820;
  return <AppScreen><Header title="Recovery" subtitle="Private progress, recorded without judgment." />
    <View style={styles.streakPanel}><LinearGradient colors={gradients.brand} style={styles.streakAccent} /><View style={[styles.streakMain, !wide && styles.streakMainMobile]}><View style={styles.streakCopy}><Text style={styles.kicker}>CURRENT STREAK</Text><View style={styles.streakValueRow}><Text style={styles.streakNumber}>{stats.currentStreak}</Text><View><Text style={styles.streakUnit}>days sober</Text><Text style={styles.since}>{data.recovery.startDate ? `Since ${formatDate(data.recovery.startDate, { month: 'long', day: 'numeric', year: 'numeric' })}` : 'Add a start date in Settings'}</Text></View></View></View><View style={styles.streakStats}><DarkStat value={`${stats.longestStreak}`} label="Longest streak" /><DarkStat value={`${stats.totalMet}`} label="Goal-met days" /><DarkStat value={`${Math.round(stats.consistency)}%`} label="Check-in rate" /></View></View><Text style={styles.motivation}>{data.recovery.motivation || 'The next supportive choice matters more than a perfect day.'}</Text></View>

    <Pressable accessibilityRole="button" onPress={() => router.push('/support')} style={({ pressed }) => [styles.support, { borderColor: theme.colors.border, backgroundColor: theme.colors.surface }, pressed && styles.pressed]}><View style={styles.supportLine} /><View style={styles.supportIcon}><Ionicons name="heart-outline" size={21} color={colors.coral} /></View><View style={styles.flex}><Text style={[styles.supportTitle, { color: theme.colors.text }]}>I need support right now</Text><Text style={[styles.meta, { color: theme.colors.muted }]}>Breathe, use your coping plan, or reach a real person.</Text></View><Ionicons name="arrow-forward" size={18} color={theme.colors.muted} /></Pressable>

    <View style={[styles.columns, !wide && styles.stack]}><Card style={styles.calendar}><SectionTitle eyebrow="RECOVERY CALENDAR" title={currentMonth.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })} /><RecoveryCalendar checkins={data.recoveryCheckins} /></Card><View style={styles.side}><View style={styles.today}><SectionTitle eyebrow="TODAY" title={todayCheck ? 'Check-in recorded' : 'Take a moment'} />{todayCheck ? <><View style={styles.todayStatus}><View style={[styles.statusMark, { backgroundColor: todayCheck.status === 'met' ? colors.success : todayCheck.status === 'difficult' ? colors.amber : colors.coral }]} /><View><Text style={[styles.savedTitle, { color: theme.colors.text }]}>{todayCheck.status === 'met' ? 'Goal met' : todayCheck.status === 'difficult' ? 'A difficult day, met honestly' : 'Lapse recorded with care'}</Text><Text style={[styles.meta, { color: theme.colors.muted }]}>Mood {todayCheck.mood}/5 · Cravings {todayCheck.craving}/5</Text></View></View><Button label="Update check-in" variant="secondary" onPress={() => router.push('/recovery-checkin')} /></> : <><Text style={[styles.body, { color: theme.colors.muted }]}>No recovery check-in today. Notice what you need without grading the answer.</Text><Button label="Start daily check-in" icon="arrow-forward" onPress={() => router.push('/recovery-checkin')} /></>}</View><View style={[styles.consistency, { borderColor: theme.colors.border }]}><SectionTitle eyebrow="CONSISTENCY" title="Showing up counts" /><ProgressBar value={stats.consistency} label="Check-in rate" detail={`${Math.round(stats.successRate)}% of logged days met your goal.`} /><Text style={[styles.encouragement, { color: theme.colors.muted }]}>A lapse does not erase the days, skills, or insight you built before it.</Text></View></View></View>
    <View style={[styles.privacy, { borderColor: theme.colors.border }]}><Ionicons name="lock-closed-outline" size={17} color={colors.purple} /><Text style={[styles.privacyText, { color: theme.colors.muted }]}>Recovery activity is never public. Notification wording and milestones stay under your control.</Text></View>
  </AppScreen>;
}

function DarkStat({ value, label }: { value: string; label: string }) { return <View style={styles.darkStat}><Text style={styles.darkStatValue}>{value}</Text><Text style={styles.darkStatLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({ streakPanel: { backgroundColor: '#111827', borderRadius: radius.lg, padding: spacing.xl, overflow: 'hidden' }, streakAccent: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 4 }, streakMain: { flexDirection: 'row', justifyContent: 'space-between', gap: 28 }, streakMainMobile: { flexDirection: 'column', gap: 20 }, streakCopy: { flex: 1 }, kicker: { color: '#9EA6B5', ...typeScale.caption, fontWeight: '600', letterSpacing: 1.35 }, streakValueRow: { flexDirection: 'row', alignItems: 'baseline', gap: 10, marginTop: 6 }, streakNumber: { color: colors.white, fontSize: 48, lineHeight: 52, fontWeight: '700', letterSpacing: -1.5 }, streakUnit: { color: colors.white, ...typeScale.bodyLarge, fontWeight: '600' }, since: { color: '#9EA6B5', ...typeScale.caption, marginTop: 2 }, streakStats: { flexDirection: 'row', gap: 22, alignItems: 'center' }, darkStat: { minWidth: 80 }, darkStatValue: { color: colors.white, fontSize: 21, lineHeight: 26, fontWeight: '700' }, darkStatLabel: { color: '#9EA6B5', ...typeScale.caption, marginTop: 2 }, motivation: { color: '#C8CED8', ...typeScale.body, borderTopWidth: 1, borderTopColor: '#293142', paddingTop: 15, marginTop: 20 }, support: { minHeight: 70, borderWidth: 1, borderRadius: radius.md, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 12, overflow: 'hidden' }, supportLine: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 3, backgroundColor: colors.coral }, supportIcon: { width: 38, height: 38, borderRadius: radius.md, backgroundColor: colors.coralSoft, alignItems: 'center', justifyContent: 'center' }, supportTitle: { ...typeScale.body, fontWeight: '600' }, meta: { ...typeScale.caption, marginTop: 2 }, pressed: { opacity: 0.75 }, flex: { flex: 1 }, columns: { flexDirection: 'row', gap: 18, alignItems: 'flex-start' }, stack: { flexDirection: 'column' }, calendar: { flex: 1.15 }, side: { flex: 0.85, gap: 22 }, today: { paddingTop: 3 }, todayStatus: { flexDirection: 'row', gap: 10, alignItems: 'center', marginBottom: 16 }, statusMark: { width: 8, height: 38, borderRadius: 4 }, savedTitle: { ...typeScale.body, fontWeight: '600' }, body: { ...typeScale.body, marginBottom: 16 }, consistency: { borderTopWidth: 1, paddingTop: 20 }, encouragement: { ...typeScale.caption, marginTop: 14 }, privacy: { borderTopWidth: 1, paddingTop: 15, flexDirection: 'row', alignItems: 'center', gap: 9 }, privacyText: { ...typeScale.caption, flex: 1 } });
