import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, View, useWindowDimensions } from 'react-native';
import { Text } from '@/components/AppText';
import { RecipeImage } from '@/components/NutritionUI';
import { AppScreen, Button, EmptyState } from '@/components/ui';
import { colors, radius, typeScale } from '@/constants/theme';
import { meals } from '@/data/catalog';
import { useTheme } from '@/hooks/useTheme';
import { useApp } from '@/state/AppProvider';
import type { GroceryCategory } from '@/types/models';
import { formatQuantity } from '@/utils/grocery';

const categories: GroceryCategory[] = ['Produce', 'Meat & Protein', 'Grains & Bakery', 'Dairy & Refrigerated', 'Canned & Pantry', 'Frozen', 'Other'];

export default function RecipeDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const theme = useTheme(); const { width } = useWindowDimensions(); const { data, toggleSavedMeal, logMeal, addMealToGrocery } = useApp(); const [notice, setNotice] = useState('');
  const recipe = useMemo(() => meals.find((meal) => meal.id === id), [id]); const wide = width >= 820;
  if (!recipe) return <AppScreen><Back /><EmptyState icon="restaurant-outline" title="Recipe not found" body="This recipe may no longer be available." /></AppScreen>;
  const saved = data.savedMeals.includes(recipe.id);
  return <AppScreen><Back />
    <View style={[styles.hero, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><RecipeImage meal={recipe} height={wide ? 360 : 240} /><View style={styles.heroCopy}><Text style={styles.cuisine}>{recipe.cuisine?.toUpperCase() ?? recipe.category.toUpperCase()}</Text><Text style={[styles.title, { color: theme.colors.text }]}>{recipe.title}</Text><Text style={[styles.description, { color: theme.colors.muted }]}>{recipe.description}</Text></View></View>
    <View style={[styles.nutrition, { borderColor: theme.colors.border }]}><Nutrition label="Calories" value={`${recipe.calories}`} /><Nutrition label="Protein" value={`${recipe.protein}g`} /><Nutrition label="Carbs" value={`${recipe.carbs}g`} /><Nutrition label="Fat" value={`${recipe.fat}g`} /></View>
    <View style={styles.details}><Detail icon="restaurant-outline" label="Serving" value={recipe.servingSize} /><Detail icon="time-outline" label="Prep" value={`${recipe.prepTime} min`} /><Detail icon="flame-outline" label="Cook" value={`${recipe.cookTime} min`} /><Detail icon="speedometer-outline" label="Difficulty" value={recipe.difficulty} /></View>
    <View style={[styles.columns, !wide && styles.stack]}><View style={styles.column}><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Ingredients</Text><Text style={[styles.sectionIntro, { color: theme.colors.muted }]}>Everything needed for {recipe.servings} serving.</Text>{categories.map((category) => { const group = recipe.ingredients.filter((ingredient) => ingredient.category === category); return group.length ? <View key={category} style={styles.ingredientGroup}><Text style={styles.groupLabel}>{category.toUpperCase()}</Text>{group.map((ingredient) => <View key={`${ingredient.name}-${ingredient.unit}`} style={[styles.ingredient, { borderColor: theme.colors.border }]}><Text style={[styles.ingredientName, { color: theme.colors.text }]}>{ingredient.name}</Text><Text style={[styles.quantity, { color: theme.colors.muted }]}>{formatQuantity(ingredient.amount, ingredient.unit)}</Text></View>)}</View> : null; })}</View>
      <View style={styles.column}><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Directions</Text><Text style={[styles.sectionIntro, { color: theme.colors.muted }]}>Read through once before you start.</Text>{recipe.instructions.map((instruction, index) => <View key={instruction} style={[styles.step, { borderColor: theme.colors.border }]}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{index + 1}</Text></View><Text style={[styles.stepText, { color: theme.colors.text }]}>{instruction}</Text></View>)}</View></View>
    <View style={[styles.actionPanel, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><Text style={[styles.actionTitle, { color: theme.colors.text }]}>Make this meal work for your week</Text>{notice ? <View style={[styles.notice, { backgroundColor: theme.isDark ? '#12302B' : colors.successSoft }]}><Ionicons name="checkmark-circle" size={18} color={colors.success} /><Text style={[styles.noticeText, { color: theme.isDark ? '#9CE0CF' : colors.success }]}>{notice}</Text></View> : null}<View style={styles.actionGrid}><Button label="Add to grocery list" icon="basket-outline" onPress={() => { addMealToGrocery(recipe.id); setNotice('Ingredients added and combined with your list.'); }} /><Button label={saved ? 'Saved recipe' : 'Save recipe'} icon={saved ? 'heart' : 'heart-outline'} variant="secondary" onPress={() => { toggleSavedMeal(recipe.id); setNotice(saved ? 'Removed from favorites.' : 'Saved to My Favorites.'); }} /><Button label="Log this meal" icon="checkmark-circle-outline" variant="secondary" onPress={() => { logMeal(recipe.id); setNotice('Meal logged for today.'); }} /><Button label="Add to weekly plan" icon="calendar-outline" variant="secondary" onPress={() => router.push(`/meal-plan?mealId=${recipe.id}` as never)} /><Button label="Swap meal" icon="refresh" variant="ghost" onPress={() => router.replace('/(tabs)/nutrition')} /></View></View>
  </AppScreen>;
}

function Back() { const theme = useTheme(); return <Pressable accessibilityRole="button" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={theme.colors.text} /><Text style={[styles.backText, { color: theme.colors.text }]}>Recipes</Text></Pressable>; }
function Nutrition({ label, value }: { label: string; value: string }) { const theme = useTheme(); return <View style={styles.nutritionItem}><Text style={[styles.nutritionValue, { color: theme.colors.text }]}>{value}</Text><Text style={[styles.nutritionLabel, { color: theme.colors.muted }]}>{label}</Text></View>; }
function Detail({ icon, label, value }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string }) { const theme = useTheme(); return <View style={[styles.detail, { borderColor: theme.colors.border }]}><Ionicons name={icon} size={18} color={colors.purple} /><View><Text style={[styles.detailLabel, { color: theme.colors.faint }]}>{label}</Text><Text style={[styles.detailValue, { color: theme.colors.text }]}>{value}</Text></View></View>; }

const styles = StyleSheet.create({ back: { alignSelf: 'flex-start', minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 8 }, backText: { ...typeScale.body, fontWeight: '600' }, hero: { borderWidth: 1, borderRadius: radius.lg, overflow: 'hidden' }, heroCopy: { padding: 20 }, cuisine: { color: colors.purple, ...typeScale.caption, letterSpacing: 1.3, fontWeight: '600' }, title: { fontSize: 30, lineHeight: 37, fontWeight: '700', marginTop: 4 }, description: { ...typeScale.bodyLarge, marginTop: 7, maxWidth: 760 }, nutrition: { borderTopWidth: 1, borderBottomWidth: 1, paddingVertical: 16, flexDirection: 'row', flexWrap: 'wrap' }, nutritionItem: { minWidth: 82, flex: 1 }, nutritionValue: { fontSize: 22, lineHeight: 28, fontWeight: '700' }, nutritionLabel: { ...typeScale.caption }, details: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, detail: { flexGrow: 1, flexBasis: 210, borderWidth: 1, borderRadius: radius.md, minHeight: 62, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 10 }, detailLabel: { ...typeScale.caption }, detailValue: { ...typeScale.body, fontWeight: '600', flexShrink: 1 }, columns: { flexDirection: 'row', gap: 28, alignItems: 'flex-start' }, stack: { flexDirection: 'column' }, column: { flex: 1, width: '100%' }, sectionTitle: { ...typeScale.section, fontWeight: '700' }, sectionIntro: { ...typeScale.body, marginTop: 2, marginBottom: 10 }, ingredientGroup: { marginTop: 12 }, groupLabel: { color: colors.purple, ...typeScale.caption, fontWeight: '600', letterSpacing: 1 }, ingredient: { minHeight: 45, borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14 }, ingredientName: { ...typeScale.body, textTransform: 'capitalize' }, quantity: { ...typeScale.label, fontWeight: '600' }, step: { borderTopWidth: 1, paddingVertical: 14, flexDirection: 'row', gap: 12 }, stepNumber: { width: 28, height: 28, borderRadius: radius.sm, backgroundColor: colors.purple, alignItems: 'center', justifyContent: 'center' }, stepNumberText: { color: colors.white, ...typeScale.label, fontWeight: '700' }, stepText: { ...typeScale.body, flex: 1 }, actionPanel: { borderWidth: 1, borderRadius: radius.lg, padding: 18 }, actionTitle: { ...typeScale.section, fontWeight: '700' }, actionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginTop: 14 }, notice: { marginTop: 12, borderRadius: radius.md, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 7 }, noticeText: { ...typeScale.label, fontWeight: '600' } });
